#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:nil broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Fotogammetria 2.
#+date: 2023
#+author: Kalicz Péter
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3)
#+latex_class: article
#+latex_class_options:
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[hungarian]{babel}
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex

* Kezdés
08:15-től kezdenénk

* Szervezési kérdések
Péter tavaly véletlenül régit vett fel.

Vizsgával elmaradtak páran. CV-s vizsgát meg kell
csinálni annak, aki folytatni akarja.

Feladatokkal kapcsolatos elmaradások. 1 héten belül pótolni.

Meher, Evelin, Szendery Gergely. Mi is!

* Anyag
Az első féléveset folytatjuk. Mindenkinek megvannak
az alapfogalmak. Érdemes átismételni.

2 db ZH a félév során. Az első a tavalyi anyagról is
szól. Áttekinteni az alapfogalmakat.

Korrábbi google drivet OneDrivera cseréljük.

* Ismétlés
** Foglalma
Fotogammetria. Fényképmérés, mennyiségi információ szerzés
a tárgyakról objektumokról, fénykép készítés és kiértékelés.
Képek és objektumok közötti matematikai kapcsolat. Centrális
vetítés tulajdonságai alapján.
** Felosztás
Eszköz: űr, légi, földi, eszközök mozgásban vannak így hordozó
eszköz alapján

Média: fotográfiai rendszerek, digitális érzékelővel.
Analóg és digitális képek.

Kiértékelés:
- Analóg :: analóg képekkel, analóg módszerrel optikai, mechanikai eszközök.
  nem kell számítás. Grafikus kiértékelés
- Analitikis :: analóg -> digitális. Analóg képekkel, számítással tárgykoordinátákat.
  Műszeerei a mérő mikroszkópok, vagy komparátorok, képi koordinátát mérünk, meghatározunk.
- digitális. Digitális -> digitális. Analitikushoz közel. Képi
  koordináta helyett pixel koordinátákat mérünk, amelyeket képi
  koordinátává alakítunk. Sok lépést automatizálhatóvá tesz. Korábban
  rengeteg emberi munka. Ez akár teljesen automatikus munkafolyamta.

Milyen koordinátát kapunk:
Centrális vetítés 1 kép x,y koordináta csak z függvényében.
Megadott síkra vetítve.

Ha mindhárom koordináta, sztereo fotogammetria. Ma inkább
több képes fotogammetria. Ma ez a jellemző.

** Centrális vetítés
Legfontosabb tulajdonságai.
- Egyenes képe egyenes
- Hasonlóság kizárólag akkor van, ha a tárgysík és a
  képsík párhuzamos


Alapvető számítások
Kép méretaránya = képen mért távolság/terepi távolság
M_k = c / h_0

h_0 = c/M_k

c = M_k * h_0

Gyakorlatban méretarányszám
M_k = c/ h_0 = 1/A_k

A_k = h_0/c 

Bázis és sortávolság

B = s * (1-p)

A = s * (1-q)

** Fényképezési felvevőrendszer
Feketedési görbe a filmek esetén. Adott megvilágítás
hatására a fény hogyan feketedik.

Feketedés logaritmikus. A filmre jutó és átjutó fény aránya.
Ha mind átjut, akkor nincs 0.
1/10-ét engedi át = 1
1/100-át = 2
1/1000 = 3

Van egy alapfátyol. Nem nulláról indul. Alapfátyol.
x tengelyen a 

Egy idő után eléri a legnagyobb feketedés, utána lekonyul.
Egy idő után roncsolja az ezüstöt.

Fontos a meredekség. Keménységgel összefügg. Meredek
kontrasztos, lapos lágy, nem kontrasztos.

Hol kezd feketedni.

** Mérőkamerák
Belső tájékozás ismerte. Vetítési középpont és képsík
egymáshoz való viszonya. Kameraállandó.
Képsík melyi pontja fölött, alatt.

Képfőpont. Az amelyik a vetítési középpont képsíkra
eső merőleges vetülete.

Optikai elrajzolás ismerete. Jobb ha külön vesszük a belső
tájékozástól. Optikai renszer nem teljesen a centrális
szerint képez. Lyukkamera a tökéletes. Optikán többszörösen
megtörő fény. Belépő és kilépő sugár szögének különbsége.

Nagy képméret. Pontos méréshez kell. Kiegészítő információ.
Magasságmérő, óra, libella...

Digitális kameránál az exif adatokban kiegészítő információ.

Exponált filmen a képi koordináta renszer. Keretjelek a kameráknál.
A fénykép felvételen a képi koordináta renszert határozza
meg. Rézau háló, illetve keretjelek.

** Digitális mérőképek
Digitális kép szabályos adatmodell. Pixelek mennyiségi infót
tartalmaz. Objektum spektrális és radiometriai adataival 
arányos. Geom, spekt, radio, időbeli felbontás.

Helyigény. pixel, sor, oszlop, radiometriai felbontás

V = ns * n oszlop * sáv * radometriai felbontás.

bit vagy bájt a felbontás Számítógépnél bájt a felbontás.

12 bit is 2 bájton tárolt.

** Digit mérőkam csoportosítása
Kép szenzorok, sorszenzorok. Ez a két nagy csoport.

** Korszerű digitális mérőkamera
Vexel ultracam leginkább használatos. Magyar 

ULTRACAM D, X, Xp képszenzoros

Sorszenzoros Leica ADS

** Sztereoszkopikus látás
3 feltétel 

képpár, tájékozás, képek szétválasztás

Képpár két külön álláspont, de ugyan az az objektum
parallaxis

tájékozás: zavartalan.

Jobb szem jobb kép

** Szétválasztás
- térben, tükrös, lencsés
- időben folyadékkristályos
- spektrálisan anaglif
** Normál sztereogram
Már tájékozott a sztereogram.
Normál sztereogramnál a bázisra merőleges kameratengellyel
készülnek a felvételek. Egyszerűbb számítás. Kis szögek
függvényeivel nem kellett foglalnkozni.

\Delta h = ...

h_0-t érdemes kieelni. Olyan mértékegység ami kell.

\delta p / p' / \delta p 

Egy arány. Nem kell átváltani. Repülési magasság mekkora
része a magasság.
** Analóg fotogammetria
mechanikai vagy optikai eszközökkel állítjuk helyre.

** Analitikus
Analitikus, mérjük számolunk, mérő

** Digitális
digitális képek, digitális kiértékelés
pixel, képi térbeli koord

** Téjékozás
Belső vetítési sík és kép viszonya
képfőpont eltolódás és kamera állandó.

Analóg képeknél kell a keretjel is.

Digitális képnél nem kell keretjel.



** Külső tájék
Már tájékozott képünk 6 paraméter
x, y, z, x_0, y_0, z_0, xc, yc, zc

Koordináta tngelyek körüli forgatás
\omega, \phi, \kappa


** Többképes fogo
Egymáshoz tájékozni. Relatív vagy kölcsönös tájékozás
Kapcsoló pontok vagy gruber pontok

5 paraméter 6 pont 1 fölös mérés.

1 pont 1 egyenlet. Relatív tájékozásra térmodell jön létre
objektum lekicsinyített képe.

Térmodell abszolút értelem.

3 koordináta eltolás és három forgatási szög.

Abszolút eltol, beforgat és méretarány összesen 7 parméteres
transzformáció. Geodéziában sokat használjuk.

1 * 6 

12 összesen.

Relatív 5 sokféle lehet!
5 szögérték, egy adott egységnyi.
2 távolság 3 szög

Sokféle fontos. Műszerek hozzá tájékozásnál volt fontos!

** UAV
pilóta nélküli eszközök.
Kategóriák

- nyílt open
- speciális specialised
- engedélyköteles certified

Nyílt kategóriával foglalkoztunk.
UAV felmérés a határokat túlléphetjük.

Mit léphetünk túl. Folyamatos eszköz követés. Gyakran
nem oldható meg. Urban canyon, erdő nem mindig!

120 m korlát is probléma lehet.

** Kérdés
Nem volt. Úgy kezdjük a félévet, hogy ne legyen gond.

* Idei anyag

** Fotogammetriai munkafolyamat

kb. 180 éves múlt

19. század elején daguerre-lips eljárás 1839?
Azért ez, mert a párizsi akadémia megvette és
ingyen elérhetővé tette. Dagerrotipia magyarul
megjlent 1840-es évek elején magyarok is.

19. század végén az elve. Meiderbaur cikke.
Újsághy Zsigmond erdőmérnök hallgató.

Elsősorban mennyiségi információ objektum mérete.

** ASPRS
1980-as def.

tárgyakról és környezetről megbízható információ
előállítás művészete, tudománya. fényképek és más
elektroágneses sugárzás készítés mérés és értelmezés

Fotointerpretáció a következő félévben.

art science technology, de alapvetően tudomány.
Művészi oldal az építészeti fotogammetria.

** Csoportosítás
Ismételtük

** Analóg fotogammetria
első félévben volt

Egy képes műszerek képtranszformátorok.
Sík, képtarszformátor SEG, LUZ átrajzoló

két képes a benti KERN pg műszer, Vild műszerei

Multiplex több képes vetítő

** Analitikus fotogammetria
mono és sztereokomparaátor

** Digitális fotogammetria
Elsődleges és másodlagos.

Másodlagos meglévő eljárással Elsődleges, digitális mérőkamerával.

Digitáilis képek és fotogammetriai szoftver és speciális
hardver eszköz.

Fotogammetriai szoftver, ami munkafolyamatot biztosítja.
Kép tájékozás és kiértékelés

Speciális hardverek 3D megjelenítők. Sztereo monitorok,
3D egér. Z kerék, amivel mérőjel magasságát állíthatjuk.

** Jelenlegi 
Leica RC30 (Wild RC-20)

Z/I imagink RMK (Zeiss RMK Top)

HM Zrínyi videója. Utolsó misszió. Lezárult korszak.
Ma már analóg kamerával nem dolgozik senki.

Analóg mérőkamerák jellemzői nem részleteztük.

** Fotogammetriai szkennerek
- Leica Geosystem

Mi a különbség?
Nem a felbontás, hanem a geometriai pontosság.

Asztali 3600 dpi sem ritka

25.4/3600
[1] 0.007055556

7 mikront általában tudja egy jobb szkenner.

Fontos a geometriai pontosság. 2 kép egymás után kivonjuk
Nagyon durva (10 pixeles eltérés is lehet), ahogy húzza.

Fotogammetria 10 um mellett 2 um RMSE!!!!

Méret Nagy méretet keeli

FÖMI DLA Leica Geosytem DSW 700

Kamerát mozgat a film előtt több képet csinál, abból
teszi össze!

Vexcel Imaging UltraScan = több érzékelőből ez is!


Z/I Imagin Phot can HM Zrínyi archívum digitális.
30*30-as filmek nem fért be.

Vehrli RasterMaster ezt is tudja.

Ingyen kapcsolatokon kapták, angliából jött.
Egy idő után nem kellenek. Teljes értéket kap a digitalizáltság.

Geometriai pontosság a legfontosabb a megfelelő
képméret mellett.

Vexcel UltraCamD
Vexcel UltraScan

Gráci professzor dogozta ki az eljárást.
9 kis szenzor előállítása töredék költség. tömeggyártásból
készült fullframe szenzorok!

Rögtön piacvezető.

** Megvan a digitális kép
Szoftver tudja a belső és külső tájékozást
relatív és abszolút

Kimenet ortofotók, ortofotó mozaikok. Térbeli
méréseket végezni a képpárokon. Kéegyeztetésekből
automatikusan pontfelhőt állítunk elő.

Térbeli mérések, ortofotó a számítás technika fejlődése
Ma már feldolgozás Imaga Matching automatikus képegyeztetés
és pontfelhő előállítása.

TRUE orto, pontfelhőn mérhetünk. Élek keresése pl. épület.

** Belső tájékozás
minimum 3 paraméter (c, F'(\ksi_0, \eta_0))

TopoxMap ablaka.

Keretjelek megmérése. Digitális fotogammetriai szoftverekben
a keretjel mérése automatizálható.

Korszerűbb kameránál a keretjel kódolt.

Sok szkenner szkenneléskor detektálja a keretjelet.
Ki tudja a fájl mellé tenni a keretjel koordinátáját!

Másodlagos képeknél a keretjelek megmérése jól automatizálható.

Agisoft PhotoScan
Kamera állandó, kalbrációs paraméterek.

** Relatív tájékozás
Kölcsönös tájékozás

5 paraméter több minden is lehet.

x iárnyú bázis rögítve. Jobb képet tologatom. forgatom.

Bal képet rögítem, nem kell továbbmenetnél mozgatni. Nem
kell elrontani a képpárokat. Korábban a
kivetített 5 paraméter

b_x válsztott, b_y, b_z, \phi_2, \omega_2, \kappa_2

*** Csak szögekkel
\phi_1, (\omega_1), \kappa_1, \phi_2, \omega_2, \kappa_2

*** Realív
Grube pontok

Koplanaritás kapcsolópontok egy síkon.

Ma már jól automatizált. Gyorsítani lehet, ha egy-két
paramétert meghatározunk, akkor csak finomítunk.

Jó kezdeti paraméterekkel gyorsabb.

5, de
Gyakorlatilag minimum 6 pont!

**** Képegyeztetés
Ma ez is már fontos lehet.

*** Abszolút tájékozás
6 paraméter X_0, Y_0, Z_0, \phi_0, \omega_0, \kappa_0

Jellemzően, ha vannak elérhető direkt tájékozás,
de indirekt úton pontosítjuk.

Direkt a kép készítésekor határozzuk meg a hat

GNSS X_0, Y_0, Z_0,
IMU/INS: \phi_0, \omega_0, \kappa_0

90-es évektől már van direkt információ. Manapság is
indirekt úton pontosítunk. Illesztő pontokk
IP, GPC (ground control points) kollinearitás elvével
történik.

Kollinearitás illesztőpont, illesztőpont képe és vetítési középpont.

3 egymást megsző egyenes. metszés, vetítési középpont és
forgatási szögek meghatározása.

1 ilelsztőpont két egyenlet, két egyenletekből három pont kell!

Relatív tájékozás után abszoltút tájékozás.

3 illesztőpont a hét paramétert is meghatározhatóvá teszi.

Illesztő pont, mid a képen és a terepen is jól azonosítható!

** Ortofotó előállítása
Tájékozott fényképből előállítható. Felületet definiálni.

Síkfelólet, homlokzat modellje, borított felszín modell.
visszavetítjük. több 100 több 1000 képből manapság. Ortofotó
mozaik.

Ez lehet az egyik kimenet.

** Ortorektifikáció
Raszter transzformáció. Fordítva haladunk.
Definiáljuk a kimeneti ortofotónkat. Milyen területre,
milyen felbontással készíten.

Veszem a pixelt térbeli egyenes a vetítési középponton,
ak képi pixelt másolom.

Ha nem sík területen, a domborzatmodellre vetítem
először. Pixelről pixelre a differenciális képátlakítás.

Fontos az újra mintavételezés resampling. Nem biztos, hogy
egy pixel. Hogyan veszem a több pixelből a mintát?

Milyen modellre? Ha DDM-re klasszikus, ha BFM, akkor true
ortofotó.

** Térbeli mérések
Manuális sztereofotogammetriai munkaállomáson. Térmodellen
irányzott pont, CAD szerű szoftveren rajzolunk (merőlege,
párhuzamos rajzolás)

Félautomatikus mérések. Több mintent jelent. Cursor-on-surface
kattintottm, s térmodellre a mérőjelet.
Bal kattint. Megkeresi a másik képen az epipoláris modell a képpáron.

Azután szabályos rácshálón maga kereste a 3D-t.

Manapság teljesen automatikusan minden pixelnek megkeressük
a párját. Sűrű pontfelhő ponthalmaz!

** Térbeli kép
Epipolásir sík a másik képen epipoláris egyenest határoz meg.
A szakaszon tudjuk ott a pont. Korreláltatjuk a képet,
megvan a pont.

** Image matching
Manapság ezek a legfontosabb kimenet.

Többféle van, majd részletesen vesszük.
Egy pontfelhő áll elő eredményként. Zajos, elszállt
pontok, kiszűrése. Modellek előállítása

BFM borított felszín modell, DSM digital surface modell.

Ezzel a félév során foglalkozunk.

** Nem képegyeztetés pontfelhő
Még fogunk foglalkozni lézerszkennerrel.
Egyéb pontfelhő feldolgozások.

Első ismétlő ZH. CV-sek miatt a harmadik héten.
18-án kerülne sor.

10 perces valami. Hasonló a beugróhoz.

* <2023-09-11 h>
Terem a tavalyival szemben.

** Soproni fényképezés

5 évente lombtalan. 20 cm felbontás 200 km^2

Nap állása >= 25 fok. Március végén tipikusan lombtalan. Tavaszi napforduló után,
de többség nem lombosodik.
Tavasszal sokkal jobb megvilágítási viszonyok.

** Belváros
Nagyobb átfedés, modellezés. Nagyobb felbontás 5cm.

** Tájékozás
Mindig szükség van indirekt javítsra. Illesztőpont segítségével.
Van repüléstervező szoftver, ami a légi háromszögelés tervezésénél ad
javaslatot, hogy hová tegyük az illesztőpontokat.

Kép kék repülési sáv, zöld tervezett illesztőpontok. Tömb sarkaiba illesztő pont.
Nem a legszéle, hogy 2–3 képen lehessen mérni az illesztőpontokra. Fertő kritikus.
Nehéz közlekedni és nehéz illesztőpontot mérni.

Illesztőpont: fontos az azonosíthatóság és megközelíthetőség.
- Előre lejelölt illesztőpont. Repülés előtt lejelölve.
- Nem jelölünk le. A képanyagon válaszatunk és bemérjük.

Az utólagos illesztőpont bemérésben van kockázat. Az IDŐ!
Felfestés, amin autó áll. Képanyagot később kapjuk, mire választunk,
nincs ott az objektum. Időráfordítás kisebb. Előzetes jelölésnél mégsem
akkor lesz a repülés. Megsemmisül.

Természeti területen nem nagyon van utólagos jelölhető illesztőpont. Fertő, erdő.
Ekkor érdemes jelölni!

Ha kimegyünk nem egyet, hanem egy csoportban 2–3. Így lesz illesztőpont és kontroll pont is,
ha már egyszer kimegyünk.

Csatorna fedlap közepe. 20 cm felbontásnál megygyőződni, hogy a képen jól elkülönül-e?
Képkészítés pillanatában átmegy egy autó. Mindig legyenek tartalék pont!!!!

Csoportos illesztő pontok a belvárosban.

Repülés 2020-03-20
Cesna gép UltraCam Eagle Mark 2 f100
100.5 mm fókusz
1/350 sec 
Tiszta égbolt.

7 sor

Megvalósulás trakje. Elég kesze-kuszának tűnik. Erős spirállal
emelkedő repülő. Alacsonyabbra ereszkedés. Tracklog jó a direkt
tájékozáshoz, ha a képeknek nincs. Van időbélyeg minden pontban.
Oda tudjuk csatolni a megfelelő pozícióhoz.

GPS időbélyege jó. Kamera órája hogyan van beállítva. Mennyire jól
szinkronizáltak az egyes berendezések időpontjai? Ez teszi nehézzé
a direkt tájékozást. GNNS, IMU és kamera.

Fontos a kamera kalibráció.

*** Kamera kalibrációs jegyzőkönyv
9 kép pánkromatikus és négy multispektrális rész.

Fontos, hogy a kamera kalibrációt korábban laborban végezték goniométer eszközzel.
Kamera svájcba, Herrbrugg a Wild.

Digitális kamerák gyártás után, de képanyag feldolgozás
során nem a labor adatokat, gyártó vagy cég terepi kalibrálás. Olyan területen, ahol
sok objektumot lehet mérni. Digi fotogammetria, digitális képek éles repülés közben
kalibrál. Nagyobb pontosság, mint labor. Hőmérséklet, fényviszonyok laborban mások lehetnek.

*** Légiháromszögelés
Nagy tömb légiháromszögelés eredménye.
Kapcsolópontok. Beljebb a tömbben több kép. Kapcsoló pontok a belsejében maradék eltérések,
pontossági mérőszám lesz a kamera kalibrációra.

Sopron nem kérte Ágfalva területét.

*** Pufferzóna
Nagyon fontos, nem lehet élesen meghúzni a határt. Ne maradjon ki terület. Pontosan
definiálni Korábban kimaradt Balf. A cég nem tudta, hogy Balf is Soproni községhatár.
Nem jó senkinek a pótlás.

*** Szelvényezés
EOTR szelvényezés készült. Azon belül 1000 méretarányú szelvényekig lemenően szelvényezve.
Nagy ortofotó mozaiknál fontos, hogy ne legyen nagy adatállomány! Lehet piramisréteg,
amit egyben is megfelelően kezelhetünk. Vannak állományok, amelyek a szelvényekből
virtuális rasztert készítenek.

ER Viewer egybe mozaikolt ortofotó. Megnéztük az illesztőpontot.

Van, hogy automatikus mozaikolás. Vagy a varróvonalak manuálisan is szerkeszthetők.
Megkeresni, hogy hol lehetett az illesztés. Különböző tónusok, objektumok dőlése is
fontos információ. Általában lehet látni az illesztéseket. A cég a technológia és az
alapos munka nagyban eltérő lehet. Odafigyeléssel, ahol kell kézzel belenyúlnak.

Belváros

*** Hisztogram
Egy lombtalan soha sem egy nyári felvétel dinamikája, de cserében a fák alatt utak,
épületek (épületkataszterhez). Az árnyékban is látszik nagyjából mi van.

Hagyományos ortofotó. Objektumok a talajszinten vannak a helyükön! DDM-re készül
az ortofotó! A true orto az újabb. Manapság egyre inkább használják. Egyiknek
és másiknak is előnye-hátránya. Csak egyik oldal, csak másik oldal.

Valódi ortó (true orto) épületek nem dőlnek sehol.

*** Műszaki dokumentáció
Feladat adatai. Külső tájékozás, digitális ortofotó.
Illesztőpontok és mérési jelgyzőkönyv.

Kamera jegyzőkönyv. Digitális kameránál képfőpont eltolódás gyakran 0 & 0!

Kamera kalibráció maradék hibái.

RMS 0.57 um pixel 4.6 um 1/8 pixel a maradék hiba! Maradékeltéréseknek van-e
szabályos eltolódás. Körgyűrűt látunk benne. Nem megfelelő kalibráció.

Digitális kamera a belső tájékozásnál forgatás izgalmas! 90 fokos forgatásokkal
meg lehet bonyolítani a forgatással.

Képátvitel. Kép szále felé csökken az élesség.

Szürke értékek különbözőségek a vignettálódás kalibrálására.

Repülésnél KML/KMZ a fájl.

Repülés protokollja a katonáknak leadandó a távérzékelési engedélyhez.

*** Légi háromszögelés
Trimble Match-AT
Aerial Triangulation

Ahol nem jól sikerült kiegyenlíteni. Szürke kapcsolópontok. Van ami több mint 8 képen!

Kapcsolópontok maradékhibájának a hisztogramja 0.17 a legtöbbnél.

Sorok vége felé nő az átlagos eltérés!

Direkt és indirekt tájékozás közötti különbségek.

Illesztőpontokon jelentkező eltérések. 0.43 3D vektorban.

Illesztő pontok mellett az ellenőrző pontokról is információ. Ellenőrző pontokon
nagyobb a hiba, mint az illesztőpontokon. 9, 15, 12 cm!

A városra kisebb hibák, kisebb terület, jobban egyben a tömb!

** Áttekintés
Sopron megrendeli, de térbeli mérés és teljes térképezést nem rendel meg.
Belváros 3D modellje sem került átadásra. A lehetőség adott, hogy 10 év
múlva megfelelően pontos és hiteles méréseket tud végezni!

Minden önkormányzatnak, az önkormányzati térinformatikai

** Szoftver
Trimble INFOT volt régen az egyik legjobb.
Szoftverek területén nagy választék, időben is sokat változnak.

Ma már azt mondják képegyeztetés terén van jobb szoftver. Ez már klasszikus!
Klasszikus nem mindig fejleszt olyan gyorsan.

10 komoly fotogammetriai szoftver van és fontosak a félkomolyak is pl. UAV képeire.
Félprofiból rengeteg van.

Számítástechnika is változik. Új technika és ahhoz új szoftverek.
Vannak szenzorhoz kamerához jó szoftverek. Pán és orto kromatkus összedolgozása.

A cégek általában több szoftvert használnak!

Pl LTK is Tr Infóval dolgozik, de gondolkoznak a váltáson.

** Kamerakalibráció
Ez lenne a következő előadás anyaga.

Jövő órán ZH! Lehet az óra végén írnánk. Szabadabb a vége.
Az elején előadással, utána 9.30–9.45-ig.

Szerdai gyakorlat. Küld üzenetet, hogy hol lesz.

* <2023-09-13 sze>

Óra elején nem voltam. Géza röviden összefoglalta, mi volt

Témavázlat:
TopoXmappal kezdünk, utána Agisoft, utána pontfelhős dolgok.

Tájékozás panel egy kép tájékozása volt az elején. Valamit egyszerűbb elmagyarázni.
Tájékozás

0-ban illesztőpontok, magasságot megadták, felemelkedett a modell.

** TopoXmapot nézték
Egyképes már volt.


Tömbkiegyenlítés ablak. Wild RC-20 13033

*** Projekt

*** Kamera

Keretjelek az ábrán kattinthatók.

Előbb próbából, most rendesen írjuk át a koordinátát.
TopoXmap vesszőt is tud, inkább pontot. Keretjelekben 4 mikrométer a legnagyobb
14 um a szkennelés. Itt nem jelentősek az eltérések.

NAGYON KELL FIGYELNI a forgatásra.

Vissza menni a Projektre menteni. Ment mindig az aktuálisat írja.

*** Kép
hozzáadás több 100 kép is.
Két képet 19 és 20 Shifttel kijelölni
Fontos, hogy az ecw-t adjuk hozzá!
A tif jpeg tömörítést alkalmazza. Ezt a jpeg tömörítésű tiffet topoxmap nem támogatja.
Több lehtőség. irfan view nem tömörített tiff, ecw-be átalakítható.
fentrol.hu-ról letölthető jpeg tömörítésűek, e miatt van.

*** Keretjel
Tömbkiegyenlítés modulnál a fenti Kép listában duplakatt. Rendes térképnézet, csak
minimalizálva van a TOC.
Keretjelek mért képi koordinátái. Ugyan az az esköz.
Alaphelyzet négy sarokba teszi. Közelítőleg oda tesszük. Egy körben megvan Nyomkövető nézet
duplakatt a pontra. Pontosabban meg tudjuk mérni.

A nyomkövetés méretaránya a Projekt ben megállítható Egy adott méretarányban végig megyek,
utána átállítom. Méretarány a jobb alsó sarokban.

Munka körbe-körbe megyek egyre inkább nagyítva.

Belső tájékozás maradék hibájának egy pixel alatt kell maradnia.

Forgatásokra nagyon kell figyelni. Kamera kalibrációs jegyzőkönyv úgy tartalmazza a kamerát,
ahogy a kalib jegyzőkönyv. Modern kamera a keretjel számozott.

Fentről.hu képeknél nincs mindig így. Mit kell elforgatni? Sok szabadság. 180 fokkal
el lenne forgatva, koordinátákat úgy állítom, hogy a megfelelő koordináta, előjellel
Keretjel megmérésével! Az a legegyszerűbb, ha nem változtatom meg a dolgokat.

Képfőpont eltolódást is át kell előjelezni. Az egész koordináta rendszert át kell forgatni
a szkennelésnek megfelelően!

Belső tájékozás több kép. Rég 10–100 analóg, digitálisnál 1000 nél több is lehet.

Autoatikus keretjel keresés mehet. Aktív, amin már megmértük.

Képekre katintva tud. váltani. Ment. Meg kell nézni az eredményt.
Két képnél nincs jelentősége, de sok száznál fontos, hogy jó legyen. Jó szoftver tudja.

Keretjel ablak jobb oldalán lehet átváltani.

Belső tájékozás OK. Paramétert nem tudjuk megtekinteni.

Külső tájékozás első lépése a relatív tájékozás. Kapcsoló vagy Gruber pont.

*** Tervezés nézet
Kép fülön tervezés nézet. Keletről nyugat felől. Tudom tologatni a tervezésben.
A kurzor átvált a táékozási nézetbe, akkor kappa szög is állítható.

Forgatás, és Centrum mezőbe szögeket és távolságokat írja. Kezdetleges tájékozás
kisajtolható. 60% átfedés.

9 kötőpontnak hívja, magyarban kapcsolópontnak hívjuk, nem kötőpont (angol tie pont)

9kötőpont/kép hat kapcsolópontot tesz le az átfedő területen. Nem csak leteszi,
hanem a képekre.

*** Illesztőpont lista
Előzetes elrendezés a fenti alapján

Projekt -> Mentés

Méretarány 10000

*** IP mérés
Dupla katt a kapcsoló ponton.

Először nem pontosan, csak nagyjából a két képen azonosíthatóan ugyan az a pont.
Azonosítható pontra teszem mindkét képen! Ne mozgassuk el nagyon.

Közelítőleg ugyan oda tenni az összes kapcsolópontot tenni! Fokozatosan növelem
a méretarányt a projektben. Kapcsolópont, mindkét képen jól tudjam észlelni.

Pár másodperc a képek között. Megengedett az árnyék használata. Inkább a jól felhasználhatót,
főleg, ha hosszabb idő!

Minél pontosabban azonosítható. Pixel szinten azonosítható!

Erdőterület fölött "h" gombbal hisztogram széthúzás. Jellegzetes facsúcs is lehet.
Szeles időben mozoghat a facsúcs, de ha nincs más jó is.

Villanyoszlp töve. Foltocska. Városi területen háztetők. Mozgó jármű nem jó!
Mindkét képen, pontosan tudunk mérni.

Ismétlődő mintázatoknál nagyon figyelni. Növénysorok. Biztos ugyan annak a végét!
Biztosan ugyan az legyen. Burkolati jel elszámolása!

Méretarány: 10 000 -> 4000 -> 2000 (1000)

Minél jobban azonosítsuk a kapcsolópontot.

Megvannak, ne nagyon mozgassuk el! Próbáljuk a szabályos elrendezést ne megváltoztatni.
Extrém eset pl. tó, de lehet bólya, uszadék. Geometrialiag nem lesz jó a tájékozásunk.


Ma egy képet megnéztünk.

Relatív tájékozás is kész. A modul hiányossága, hogy önmagában a relatív tájékozás
pontosságát nem látom. Abszolút tájékozás után látjuk mennyire jó.

Egy lépéses kiértékelés. Nem látom külön a relatív tájékozás jóságát.

Jövő héten szerdán valószínűleg nem lesz Géza. Valakit megkér. Másik időpontban
megtartani. Megy üzenet.
