#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:nil broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Fotogammetria 2.
#+date: 2023
#+author: Kalicz Péter
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3)
#+latex_class: article
#+latex_class_options:
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[hungarian]{babel}
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex

* Kezdés
08:15-től kezdenénk

* Szervezési kérdések
Péter tavaly véletlenül régit vett fel.

Vizsgával elmaradtak páran. CV-s vizsgát meg kell
csinálni annak, aki folytatni akarja.

Feladatokkal kapcsolatos elmaradások. 1 héten belül pótolni.

Meher, Evelin, Szendery Gergely. Mi is!

* Anyag
Az első féléveset folytatjuk. Mindenkinek megvannak
az alapfogalmak. Érdemes átismételni.

2 db ZH a félév során. Az első a tavalyi anyagról is
szól. Áttekinteni az alapfogalmakat.

Korrábbi google drivet OneDrivera cseréljük.

* Ismétlés
** Foglalma
Fotogammetria. Fényképmérés, mennyiségi információ szerzés
a tárgyakról objektumokról, fénykép készítés és kiértékelés.
Képek és objektumok közötti matematikai kapcsolat. Centrális
vetítés tulajdonságai alapján.
** Felosztás
Eszköz: űr, légi, földi, eszközök mozgásban vannak így hordozó
eszköz alapján

Média: fotográfiai rendszerek, digitális érzékelővel.
Analóg és digitális képek.

Kiértékelés:
- Analóg :: analóg képekkel, analóg módszerrel optikai, mechanikai eszközök.
  nem kell számítás. Grafikus kiértékelés
- Analitikis :: analóg -> digitális. Analóg képekkel, számítással tárgykoordinátákat.
  Műszeerei a mérő mikroszkópok, vagy komparátorok, képi koordinátát mérünk, meghatározunk.
- Digitális :: Digitális -> digitális. Analitikushoz közel. Képi
  koordináta helyett pixel koordinátákat mérünk, amelyeket képi
  koordinátává alakítunk. Sok lépést automatizálhatóvá tesz. Korábban
  rengeteg emberi munka. Ez akár teljesen automatikus munkafolyamta.

Milyen koordinátát kapunk:
Centrális vetítés 1 kép x,y koordináta csak z függvényében.
Megadott síkra vetítve.

Ha mindhárom koordináta, sztereo fotogammetria. Ma inkább
több képes fotogammetria. Ma ez a jellemző.

** Centrális vetítés
Legfontosabb tulajdonságai.
- Egyenes képe egyenes
- Hasonlóság kizárólag akkor van, ha a tárgysík és a
  képsík párhuzamos


Alapvető számítások
Kép méretaránya = képen mért távolság/terepi távolság
M_k = c / h_0

h_0 = c/M_k

c = M_k * h_0

Gyakorlatban méretarányszám
M_k = c/ h_0 = 1/A_k

A_k = h_0/c 

Bázis és sortávolság

B = s * (1-p)

A = s * (1-q)

** Fényképezési felvevőrendszer
Feketedési görbe a filmek esetén. Adott megvilágítás
hatására a fény hogyan feketedik.

Feketedés logaritmikus. A filmre jutó és átjutó fény aránya.
Ha mind átjut, akkor nincs 0.
1/10-ét engedi át = 1
1/100-át = 2
1/1000 = 3

Van egy alapfátyol. Nem nulláról indul. Alapfátyol.
x tengelyen a 

Egy idő után eléri a legnagyobb feketedés, utána lekonyul.
Egy idő után roncsolja az ezüstöt.

Fontos a meredekség. Keménységgel összefügg. Meredek
kontrasztos, lapos lágy, nem kontrasztos.

Hol kezd feketedni.

** Mérőkamerák
Belső tájékozás ismerte. Vetítési középpont és képsík
egymáshoz való viszonya. Kameraállandó.
Képsík melyi pontja fölött, alatt.

Képfőpont. Az amelyik a vetítési középpont képsíkra
eső merőleges vetülete.

Optikai elrajzolás ismerete. Jobb ha külön vesszük a belső
tájékozástól. Optikai rendszer nem teljesen a centrális
szerint képez. Lyukkamera a tökéletes. Optikán többszörösen
megtörő fény. Belépő és kilépő sugár szögének különbsége.

Nagy képméret. Pontos méréshez kell. Kiegészítő információ.
Magasságmérő, óra, libella...

Digitális kameránál az exif adatokban kiegészítő információ.

Exponált filmen a képi koordináta renszer. Keretjelek a kameráknál.
A fénykép felvételen a képi koordináta renszert határozza
meg. Rézau háló, illetve keretjelek.

** Digitális mérőképek
Digitális kép szabályos adatmodell. Pixelek mennyiségi infót
tartalmaz. Objektum spektrális és radiometriai adataival 
arányos. Geom, spekt, radio, időbeli felbontás.

Helyigény. pixel, sor, oszlop, radiometriai felbontás

V = ns * n oszlop * sáv * radometriai felbontás.

bit vagy bájt a felbontás Számítógépnél bájt a felbontás.

12 bit is 2 bájton tárolt.

** Digit mérőkam csoportosítása
Kép szenzorok, sorszenzorok. Ez a két nagy csoport.

** Korszerű digitális mérőkamera
Vexel ultracam leginkább használatos. Magyar 

ULTRACAM D, X, Xp képszenzoros

Sorszenzoros Leica ADS

** Sztereoszkopikus látás
3 feltétel 

képpár, tájékozás, képek szétválasztás

Képpár két külön álláspont, de ugyan az az objektum
parallaxis

tájékozás: zavartalan.

Jobb szem jobb kép

** Szétválasztás
- térben, tükrös, lencsés
- időben folyadékkristályos
- spektrálisan anaglif
** Normál sztereogram
Már tájékozott a sztereogram.
Normál sztereogramnál a bázisra merőleges kameratengellyel
készülnek a felvételek. Egyszerűbb számítás. Kis szögek
függvényeivel nem kellett foglalnkozni.

\Delta h = ...

h_0-t érdemes kieelni. Olyan mértékegység ami kell.

\delta p / p' / \delta p 

Egy arány. Nem kell átváltani. Repülési magasság mekkora
része a magasság.
** Analóg fotogammetria
mechanikai vagy optikai eszközökkel állítjuk helyre.

** Analitikus
Analitikus, mérjük számolunk, mérő

** Digitális
digitális képek, digitális kiértékelés
pixel, képi térbeli koord

** Téjékozás
Belső vetítési sík és kép viszonya
képfőpont eltolódás és kamera állandó.

Analóg képeknél kell a keretjel is.

Digitális képnél nem kell keretjel.



** Külső tájék
Már tájékozott képünk 6 paraméter
x, y, z, x_0, y_0, z_0, xc, yc, zc

Koordináta tngelyek körüli forgatás
\omega, \phi, \kappa


** Többképes fogo
Egymáshoz tájékozni. Relatív vagy kölcsönös tájékozás
Kapcsoló pontok vagy gruber pontok

5 paraméter 6 pont 1 fölös mérés.

1 pont 1 egyenlet. Relatív tájékozásra térmodell jön létre
objektum lekicsinyített képe.

Térmodell abszolút értelem.

3 koordináta eltolás és három forgatási szög.

Abszolút eltol, beforgat és méretarány összesen 7 parméteres
transzformáció. Geodéziában sokat használjuk.

1 * 6 

12 összesen.

Relatív 5 sokféle lehet!
5 szögérték, egy adott egységnyi.
2 távolság 3 szög

Sokféle fontos. Műszerek hozzá tájékozásnál volt fontos!

** UAV
pilóta nélküli eszközök.
Kategóriák

- nyílt open
- speciális specialised
- engedélyköteles certified

Nyílt kategóriával foglalkoztunk.
UAV felmérés a határokat túlléphetjük.

Mit léphetünk túl. Folyamatos eszköz követés. Gyakran
nem oldható meg. Urban canyon, erdő nem mindig!

120 m korlát is probléma lehet.

** Kérdés
Nem volt. Úgy kezdjük a félévet, hogy ne legyen gond.

* Idei anyag

** Fotogammetriai munkafolyamat

kb. 180 éves múlt

19. század elején daguerre-lips eljárás 1839?
Azért ez, mert a párizsi akadémia megvette és
ingyen elérhetővé tette. Dagerrotipia magyarul
megjlent 1840-es évek elején magyarok is.

19. század végén az elve. Meiderbaur cikke.
Újsághy Zsigmond erdőmérnök hallgató.

Elsősorban mennyiségi információ objektum mérete.

** ASPRS
1980-as def.

tárgyakról és környezetről megbízható információ
előállítás művészete, tudománya. fényképek és más
elektroágneses sugárzás készítés mérés és értelmezés

Fotointerpretáció a következő félévben.

art science technology, de alapvetően tudomány.
Művészi oldal az építészeti fotogammetria.

** Csoportosítás
Ismételtük

** Analóg fotogammetria
első félévben volt

Egy képes műszerek képtranszformátorok.
Sík, képtarszformátor SEG, LUZ átrajzoló

két képes a benti KERN pg műszer, Vild műszerei

Multiplex több képes vetítő

** Analitikus fotogammetria
mono és sztereokomparaátor

** Digitális fotogammetria
Elsődleges és másodlagos.

Másodlagos meglévő eljárással Elsődleges, digitális mérőkamerával.

Digitáilis képek és fotogammetriai szoftver és speciális
hardver eszköz.

Fotogammetriai szoftver, ami munkafolyamatot biztosítja.
Kép tájékozás és kiértékelés

Speciális hardverek 3D megjelenítők. Sztereo monitorok,
3D egér. Z kerék, amivel mérőjel magasságát állíthatjuk.

** Jelenlegi 
Leica RC30 (Wild RC-20)

Z/I imagink RMK (Zeiss RMK Top)

HM Zrínyi videója. Utolsó misszió. Lezárult korszak.
Ma már analóg kamerával nem dolgozik senki.

Analóg mérőkamerák jellemzői nem részleteztük.

** Fotogammetriai szkennerek
- Leica Geosystem

Mi a különbség?
Nem a felbontás, hanem a geometriai pontosság.

Asztali 3600 dpi sem ritka

25.4/3600
[1] 0.007055556

7 mikront általában tudja egy jobb szkenner.

Fontos a geometriai pontosság. 2 kép egymás után kivonjuk
Nagyon durva (10 pixeles eltérés is lehet), ahogy húzza.

Fotogammetria 10 um mellett 2 um RMSE!!!!

Méret Nagy méretet keeli

FÖMI DLA Leica Geosytem DSW 700

Kamerát mozgat a film előtt több képet csinál, abból
teszi össze!

Vexcel Imaging UltraScan = több érzékelőből ez is!


Z/I Imagin Phot can HM Zrínyi archívum digitális.
30*30-as filmek nem fért be.

Vehrli RasterMaster ezt is tudja.

Ingyen kapcsolatokon kapták, angliából jött.
Egy idő után nem kellenek. Teljes értéket kap a digitalizáltság.

Geometriai pontosság a legfontosabb a megfelelő
képméret mellett.

Vexcel UltraCamD
Vexcel UltraScan

Gráci professzor dogozta ki az eljárást.
9 kis szenzor előállítása töredék költség. tömeggyártásból
készült fullframe szenzorok!

Rögtön piacvezető.

** Megvan a digitális kép
Szoftver tudja a belső és külső tájékozást
relatív és abszolút

Kimenet ortofotók, ortofotó mozaikok. Térbeli
méréseket végezni a képpárokon. Kéegyeztetésekből
automatikusan pontfelhőt állítunk elő.

Térbeli mérések, ortofotó a számítás technika fejlődése
Ma már feldolgozás Imaga Matching automatikus képegyeztetés
és pontfelhő előállítása.

TRUE orto, pontfelhőn mérhetünk. Élek keresése pl. épület.

** Belső tájékozás
minimum 3 paraméter (c, F'(\ksi_0, \eta_0))

TopoxMap ablaka.

Keretjelek megmérése. Digitális fotogammetriai szoftverekben
a keretjel mérése automatizálható.

Korszerűbb kameránál a keretjel kódolt.

Sok szkenner szkenneléskor detektálja a keretjelet.
Ki tudja a fájl mellé tenni a keretjel koordinátáját!

Másodlagos képeknél a keretjelek megmérése jól automatizálható.

Agisoft PhotoScan
Kamera állandó, kalbrációs paraméterek.

** Relatív tájékozás
Kölcsönös tájékozás

5 paraméter több minden is lehet.

x iárnyú bázis rögítve. Jobb képet tologatom. forgatom.

Bal képet rögítem, nem kell továbbmenetnél mozgatni. Nem
kell elrontani a képpárokat. Korábban a
kivetített 5 paraméter

b_x válsztott, b_y, b_z, \phi_2, \omega_2, \kappa_2

*** Csak szögekkel
\phi_1, (\omega_1), \kappa_1, \phi_2, \omega_2, \kappa_2

*** Realív
Grube pontok

Koplanaritás kapcsolópontok egy síkon.

Ma már jól automatizált. Gyorsítani lehet, ha egy-két
paramétert meghatározunk, akkor csak finomítunk.

Jó kezdeti paraméterekkel gyorsabb.

5, de
Gyakorlatilag minimum 6 pont!

**** Képegyeztetés
Ma ez is már fontos lehet.

*** Abszolút tájékozás
6 paraméter X_0, Y_0, Z_0, \phi_0, \omega_0, \kappa_0

Jellemzően, ha vannak elérhető direkt tájékozás,
de indirekt úton pontosítjuk.

Direkt a kép készítésekor határozzuk meg a hat

GNSS X_0, Y_0, Z_0,
IMU/INS: \phi_0, \omega_0, \kappa_0

90-es évektől már van direkt információ. Manapság is
indirekt úton pontosítunk. Illesztő pontokk
IP, GPC (ground control points) kollinearitás elvével
történik.

Kollinearitás illesztőpont, illesztőpont képe és vetítési középpont.

3 egymást megsző egyenes. metszés, vetítési középpont és
forgatási szögek meghatározása.

1 ilelsztőpont két egyenlet, két egyenletekből három pont kell!

Relatív tájékozás után abszoltút tájékozás.

3 illesztőpont a hét paramétert is meghatározhatóvá teszi.

Illesztő pont, mid a képen és a terepen is jól azonosítható!

** Ortofotó előállítása
Tájékozott fényképből előállítható. Felületet definiálni.

Síkfelólet, homlokzat modellje, borított felszín modell.
visszavetítjük. több 100 több 1000 képből manapság. Ortofotó
mozaik.

Ez lehet az egyik kimenet.

** Ortorektifikáció
Raszter transzformáció. Fordítva haladunk.
Definiáljuk a kimeneti ortofotónkat. Milyen területre,
milyen felbontással készíten.

Veszem a pixelt térbeli egyenes a vetítési középponton,
ak képi pixelt másolom.

Ha nem sík területen, a domborzatmodellre vetítem
először. Pixelről pixelre a differenciális képátlakítás.

Fontos az újra mintavételezés resampling. Nem biztos, hogy
egy pixel. Hogyan veszem a több pixelből a mintát?

Milyen modellre? Ha DDM-re klasszikus, ha BFM, akkor true
ortofotó.

** Térbeli mérések
Manuális sztereofotogammetriai munkaállomáson. Térmodellen
irányzott pont, CAD szerű szoftveren rajzolunk (merőlege,
párhuzamos rajzolás)

Félautomatikus mérések. Több mintent jelent. Cursor-on-surface
kattintottm, s térmodellre a mérőjelet.
Bal kattint. Megkeresi a másik képen az epipoláris modell a képpáron.

Azután szabályos rácshálón maga kereste a 3D-t.

Manapság teljesen automatikusan minden pixelnek megkeressük
a párját. Sűrű pontfelhő ponthalmaz!

** Térbeli kép
Epipolásir sík a másik képen epipoláris egyenest határoz meg.
A szakaszon tudjuk ott a pont. Korreláltatjuk a képet,
megvan a pont.

** Image matching
Manapság ezek a legfontosabb kimenet.

Többféle van, majd részletesen vesszük.
Egy pontfelhő áll elő eredményként. Zajos, elszállt
pontok, kiszűrése. Modellek előállítása

BFM borított felszín modell, DSM digital surface modell.

Ezzel a félév során foglalkozunk.

** Nem képegyeztetés pontfelhő
Még fogunk foglalkozni lézerszkennerrel.
Egyéb pontfelhő feldolgozások.

Első ismétlő ZH. CV-sek miatt a harmadik héten.
18-án kerülne sor.

10 perces valami. Hasonló a beugróhoz.

* <2023-09-11 h>
Terem a tavalyival szemben.

** Soproni fényképezés

5 évente lombtalan. 20 cm felbontás 200 km^2

Nap állása >= 25 fok. Március végén tipikusan lombtalan. Tavaszi napforduló után,
de többség nem lombosodik.
Tavasszal sokkal jobb megvilágítási viszonyok.

** Belváros
Nagyobb átfedés, modellezés. Nagyobb felbontás 5cm.

** Tájékozás
Mindig szükség van indirekt javítsra. Illesztőpont segítségével.
Van repüléstervező szoftver, ami a légi háromszögelés tervezésénél ad
javaslatot, hogy hová tegyük az illesztőpontokat.

Kép kék repülési sáv, zöld tervezett illesztőpontok. Tömb sarkaiba illesztő pont.
Nem a legszéle, hogy 2–3 képen lehessen mérni az illesztőpontokra. Fertő kritikus.
Nehéz közlekedni és nehéz illesztőpontot mérni.

Illesztőpont: fontos az azonosíthatóság és megközelíthetőség.
- Előre lejelölt illesztőpont. Repülés előtt lejelölve.
- Nem jelölünk le. A képanyagon válaszatunk és bemérjük.

Az utólagos illesztőpont bemérésben van kockázat. Az IDŐ!
Felfestés, amin autó áll. Képanyagot később kapjuk, mire választunk,
nincs ott az objektum. Időráfordítás kisebb. Előzetes jelölésnél mégsem
akkor lesz a repülés. Megsemmisül.

Természeti területen nem nagyon van utólagos jelölhető illesztőpont. Fertő, erdő.
Ekkor érdemes jelölni!

Ha kimegyünk nem egyet, hanem egy csoportban 2–3. Így lesz illesztőpont és kontroll pont is,
ha már egyszer kimegyünk.

Csatorna fedlap közepe. 20 cm felbontásnál megygyőződni, hogy a képen jól elkülönül-e?
Képkészítés pillanatában átmegy egy autó. Mindig legyenek tartalék pont!!!!

Csoportos illesztő pontok a belvárosban.

Repülés 2020-03-20
Cesna gép UltraCam Eagle Mark 2 f100
100.5 mm fókusz
1/350 sec 
Tiszta égbolt.

7 sor

Megvalósulás trakje. Elég kesze-kuszának tűnik. Erős spirállal
emelkedő repülő. Alacsonyabbra ereszkedés. Tracklog jó a direkt
tájékozáshoz, ha a képeknek nincs. Van időbélyeg minden pontban.
Oda tudjuk csatolni a megfelelő pozícióhoz.

GPS időbélyege jó. Kamera órája hogyan van beállítva. Mennyire jól
szinkronizáltak az egyes berendezések időpontjai? Ez teszi nehézzé
a direkt tájékozást. GNNS, IMU és kamera.

Fontos a kamera kalibráció.

*** Kamera kalibrációs jegyzőkönyv
9 kép pánkromatikus és négy multispektrális rész.

Fontos, hogy a kamera kalibrációt korábban laborban végezték goniométer eszközzel.
Kamera svájcba, Herrbrugg a Wild.

Digitális kamerák gyártás után, de képanyag feldolgozás
során nem a labor adatokat, gyártó vagy cég terepi kalibrálás. Olyan területen, ahol
sok objektumot lehet mérni. Digi fotogammetria, digitális képek éles repülés közben
kalibrál. Nagyobb pontosság, mint labor. Hőmérséklet, fényviszonyok laborban mások lehetnek.

*** Légiháromszögelés
Nagy tömb légiháromszögelés eredménye.
Kapcsolópontok. Beljebb a tömbben több kép. Kapcsoló pontok a belsejében maradék eltérések,
pontossági mérőszám lesz a kamera kalibrációra.

Sopron nem kérte Ágfalva területét.

*** Pufferzóna
Nagyon fontos, nem lehet élesen meghúzni a határt. Ne maradjon ki terület. Pontosan
definiálni Korábban kimaradt Balf. A cég nem tudta, hogy Balf is Soproni községhatár.
Nem jó senkinek a pótlás.

*** Szelvényezés
EOTR szelvényezés készült. Azon belül 1000 méretarányú szelvényekig lemenően szelvényezve.
Nagy ortofotó mozaiknál fontos, hogy ne legyen nagy adatállomány! Lehet piramisréteg,
amit egyben is megfelelően kezelhetünk. Vannak állományok, amelyek a szelvényekből
virtuális rasztert készítenek.

ER Viewer egybe mozaikolt ortofotó. Megnéztük az illesztőpontot.

Van, hogy automatikus mozaikolás. Vagy a varróvonalak manuálisan is szerkeszthetők.
Megkeresni, hogy hol lehetett az illesztés. Különböző tónusok, objektumok dőlése is
fontos információ. Általában lehet látni az illesztéseket. A cég a technológia és az
alapos munka nagyban eltérő lehet. Odafigyeléssel, ahol kell kézzel belenyúlnak.

Belváros

*** Hisztogram
Egy lombtalan soha sem egy nyári felvétel dinamikája, de cserében a fák alatt utak,
épületek (épületkataszterhez). Az árnyékban is látszik nagyjából mi van.

Hagyományos ortofotó. Objektumok a talajszinten vannak a helyükön! DDM-re készül
az ortofotó! A true orto az újabb. Manapság egyre inkább használják. Egyiknek
és másiknak is előnye-hátránya. Csak egyik oldal, csak másik oldal.

Valódi ortó (true orto) épületek nem dőlnek sehol.

*** Műszaki dokumentáció
Feladat adatai. Külső tájékozás, digitális ortofotó.
Illesztőpontok és mérési jelgyzőkönyv.

Kamera jegyzőkönyv. Digitális kameránál képfőpont eltolódás gyakran 0 & 0!

Kamera kalibráció maradék hibái.

RMS 0.57 um pixel 4.6 um 1/8 pixel a maradék hiba! Maradékeltéréseknek van-e
szabályos eltolódás. Körgyűrűt látunk benne. Nem megfelelő kalibráció.

Digitális kamera a belső tájékozásnál forgatás izgalmas! 90 fokos forgatásokkal
meg lehet bonyolítani a forgatással.

Képátvitel. Kép szále felé csökken az élesség.

Szürke értékek különbözőségek a vignettálódás kalibrálására.

Repülésnél KML/KMZ a fájl.

Repülés protokollja a katonáknak leadandó a távérzékelési engedélyhez.

*** Légi háromszögelés
Trimble Match-AT
Aerial Triangulation

Ahol nem jól sikerült kiegyenlíteni. Szürke kapcsolópontok. Van ami több mint 8 képen!

Kapcsolópontok maradékhibájának a hisztogramja 0.17 a legtöbbnél.

Sorok vége felé nő az átlagos eltérés!

Direkt és indirekt tájékozás közötti különbségek.

Illesztőpontokon jelentkező eltérések. 0.43 3D vektorban.

Illesztő pontok mellett az ellenőrző pontokról is információ. Ellenőrző pontokon
nagyobb a hiba, mint az illesztőpontokon. 9, 15, 12 cm!

A városra kisebb hibák, kisebb terület, jobban egyben a tömb!

** Áttekintés
Sopron megrendeli, de térbeli mérés és teljes térképezést nem rendel meg.
Belváros 3D modellje sem került átadásra. A lehetőség adott, hogy 10 év
múlva megfelelően pontos és hiteles méréseket tud végezni!

Minden önkormányzatnak, az önkormányzati térinformatikai

** Szoftver
Trimble INFOT volt régen az egyik legjobb.
Szoftverek területén nagy választék, időben is sokat változnak.

Ma már azt mondják képegyeztetés terén van jobb szoftver. Ez már klasszikus!
Klasszikus nem mindig fejleszt olyan gyorsan.

10 komoly fotogammetriai szoftver van és fontosak a félkomolyak is pl. UAV képeire.
Félprofiból rengeteg van.

Számítástechnika is változik. Új technika és ahhoz új szoftverek.
Vannak szenzorhoz kamerához jó szoftverek. Pán és orto kromatkus összedolgozása.

A cégek általában több szoftvert használnak!

Pl LTK is Tr Infóval dolgozik, de gondolkoznak a váltáson.

** Kamerakalibráció
Ez lenne a következő előadás anyaga.

Jövő órán ZH! Lehet az óra végén írnánk. Szabadabb a vége.
Az elején előadással, utána 9.30–9.45-ig.

Szerdai gyakorlat. Küld üzenetet, hogy hol lesz.

* <2023-09-13 sze>

Óra elején nem voltam. Géza röviden összefoglalta, mi volt

Témavázlat:
TopoXmappal kezdünk, utána Agisoft, utána pontfelhős dolgok.

Tájékozás panel egy kép tájékozása volt az elején. Valamit egyszerűbb elmagyarázni.
Tájékozás

0-ban illesztőpontok, magasságot megadták, felemelkedett a modell.

** TopoXmapot nézték
Egyképes már volt.


Tömbkiegyenlítés ablak. Wild RC-20 13033

*** Projekt

*** Kamera

Keretjelek az ábrán kattinthatók.

Előbb próbából, most rendesen írjuk át a koordinátát.
TopoXmap vesszőt is tud, inkább pontot. Keretjelekben 4 mikrométer a legnagyobb
14 um a szkennelés. Itt nem jelentősek az eltérések.

NAGYON KELL FIGYELNI a forgatásra.

Vissza menni a Projektre menteni. Ment mindig az aktuálisat írja.

*** Kép
hozzáadás több 100 kép is.
Két képet 19 és 20 Shifttel kijelölni
Fontos, hogy az ecw-t adjuk hozzá!
A tif jpeg tömörítést alkalmazza. Ezt a jpeg tömörítésű tiffet topoxmap nem támogatja.
Több lehtőség. irfan view nem tömörített tiff, ecw-be átalakítható.
fentrol.hu-ról letölthető jpeg tömörítésűek, e miatt van.

*** Keretjel
Tömbkiegyenlítés modulnál a fenti Kép listában duplakatt. Rendes térképnézet, csak
minimalizálva van a TOC.
Keretjelek mért képi koordinátái. Ugyan az az esköz.
Alaphelyzet négy sarokba teszi. Közelítőleg oda tesszük. Egy körben megvan Nyomkövető nézet
duplakatt a pontra. Pontosabban meg tudjuk mérni.

A nyomkövetés méretaránya a Projekt ben megállítható Egy adott méretarányban végig megyek,
utána átállítom. Méretarány a jobb alsó sarokban.

Munka körbe-körbe megyek egyre inkább nagyítva.

Belső tájékozás maradék hibájának egy pixel alatt kell maradnia.

Forgatásokra nagyon kell figyelni. Kamera kalibrációs jegyzőkönyv úgy tartalmazza a kamerát,
ahogy a kalib jegyzőkönyv. Modern kamera a keretjel számozott.

Fentről.hu képeknél nincs mindig így. Mit kell elforgatni? Sok szabadság. 180 fokkal
el lenne forgatva, koordinátákat úgy állítom, hogy a megfelelő koordináta, előjellel
Keretjel megmérésével! Az a legegyszerűbb, ha nem változtatom meg a dolgokat.

Képfőpont eltolódást is át kell előjelezni. Az egész koordináta rendszert át kell forgatni
a szkennelésnek megfelelően!

Belső tájékozás több kép. Rég 10–100 analóg, digitálisnál 1000 nél több is lehet.

Autoatikus keretjel keresés mehet. Aktív, amin már megmértük.

Képekre katintva tud. váltani. Ment. Meg kell nézni az eredményt.
Két képnél nincs jelentősége, de sok száznál fontos, hogy jó legyen. Jó szoftver tudja.

Keretjel ablak jobb oldalán lehet átváltani.

Belső tájékozás OK. Paramétert nem tudjuk megtekinteni.

Külső tájékozás első lépése a relatív tájékozás. Kapcsoló vagy Gruber pont.

*** Tervezés nézet
Kép fülön tervezés nézet. Keletről nyugat felől. Tudom tologatni a tervezésben.
A kurzor átvált a táékozási nézetbe, akkor kappa szög is állítható.

Forgatás, és Centrum mezőbe szögeket és távolságokat írja. Kezdetleges tájékozás
kisajtolható. 60% átfedés.

9 kötőpontnak hívja, magyarban kapcsolópontnak hívjuk, nem kötőpont (angol tie pont)

9kötőpont/kép hat kapcsolópontot tesz le az átfedő területen. Nem csak leteszi,
hanem a képekre.

*** Illesztőpont lista
Előzetes elrendezés a fenti alapján

Projekt -> Mentés

Méretarány 10000

*** IP mérés
Dupla katt a kapcsoló ponton.

Először nem pontosan, csak nagyjából a két képen azonosíthatóan ugyan az a pont.
Azonosítható pontra teszem mindkét képen! Ne mozgassuk el nagyon.

Közelítőleg ugyan oda tenni az összes kapcsolópontot tenni! Fokozatosan növelem
a méretarányt a projektben. Kapcsolópont, mindkét képen jól tudjam észlelni.

Pár másodperc a képek között. Megengedett az árnyék használata. Inkább a jól felhasználhatót,
főleg, ha hosszabb idő!

Minél pontosabban azonosítható. Pixel szinten azonosítható!

Erdőterület fölött "h" gombbal hisztogram széthúzás. Jellegzetes facsúcs is lehet.
Szeles időben mozoghat a facsúcs, de ha nincs más jó is.

Villanyoszlp töve. Foltocska. Városi területen háztetők. Mozgó jármű nem jó!
Mindkét képen, pontosan tudunk mérni.

Ismétlődő mintázatoknál nagyon figyelni. Növénysorok. Biztos ugyan annak a végét!
Biztosan ugyan az legyen. Burkolati jel elszámolása!

Méretarány: 10 000 -> 4000 -> 2000 (1000)

Minél jobban azonosítsuk a kapcsolópontot.

Megvannak, ne nagyon mozgassuk el! Próbáljuk a szabályos elrendezést ne megváltoztatni.
Extrém eset pl. tó, de lehet bólya, uszadék. Geometrialiag nem lesz jó a tájékozásunk.


Ma egy képet megnéztünk.

Relatív tájékozás is kész. A modul hiányossága, hogy önmagában a relatív tájékozás
pontosságát nem látom. Abszolút tájékozás után látjuk mennyire jó.

Egy lépéses kiértékelés. Nem látom külön a relatív tájékozás jóságát.

Jövő héten szerdán valószínűleg nem lesz Géza. Valakit megkér. Másik időpontban
megtartani. Megy üzenet.

* <2023-09-18 h>
Kedves Hallgatók!

Az 1. ZH eredményei a következő táblázatban láthatók:
https://nyme-my.sharepoint.com/:x:/g/personal/kiraly_geza_uni-sopron_hu/ETwKMwpixz9Jtxiz3gC3OO8BQejMKuIT7LiqiOq22DDw5Q?e=kNzclj

A 12 emberből, aki megírta, a számolás csak 3 embernek lett jó (25%).

A kérdésekkel is voltak azért problémák, az alábbiakban szedtem össze a leggyakoribbakat:
1. 1.1.  Fotogrammetria felosztásai: itt minimum 3 felosztást kellett
   írni, és nem egyféle felosztásból 3 kategóriát! Valamint "űri"
   fotogrammetria nincs, csak űr fotogrammetria
2. 2.2.  Alapvető számolások (Mk, B, A): Sajnos ezzel nagyon sok
   probléma volt, sokan nem írták fel az alapképletet, volt aki
   rosszul írta fel az alapképletet, bázisok számolásánál pedig
   további gondok adódtak. A képi bázis (b'), amit a képen mérünk, és
   (általában mm-ben határozunk meg, a terepi bázist (B) pedig a
   "terepen" és m-ben. Sokan összekeverték a kettőt!
3. 3.2.  Mérőkamerák ismérvei: itt nagyon kevés ember volt, aki teljes
   választ írt; 1) Belső tájékozás ismerete, 2) Optikai elrajzolás
   ismerete, 3) Nagy képméret, 4) kiegészítő információk. Az első
   kettőnél fontos az "ismerete", mert pl. optikai elrajzolása minden
   kamerának van.
4. 5.1.  Mesterséges sztereoszkópikus látás feltételei: Itt 3
   feltételről beszéltünk, röviden: 1) képpár, 2) relatív
   tájékozás, 3) szétválasztás. Többen írtatok egy negyediket is, hogy
   ne legyen harántparallaxis a képek között, de pontosan ezt
   biztosítja a relatív tájékozás.
5. 6.1.  Analóg fotogrammetria: sajnos itt teljesen jó válasz talán
   nem is született. Analóg képek analóg módon történő kiértékelése. A
   vetítési sugarakat optikai és/vagy mechanikai eszközökkel állítjuk
   vissza, nincs szükség számításokra, a sík- és domborzatrajz
   grafikusan kiértékelhető.
6. 8.2.2.  Abszolút tájékozás: Lehet, hogy részemről is jobb lett
   volna, ha leszűkítem, hogy az "egyképes" vagy a relatív tájékozást
   követő abszolút tájékozást kérdeztem. Egy kép esetében az abszolút
   tájékozás teszi lehetővé a fotogrammetriai képi
   koordináta-rendszerből való áttérést a térbeli (általában EOV)
   koordináta-rendszerbe. Egy kép esetében 6 külső tájékozási
   paraméter van: X0, Y0, Z0, omega, fi, kappa. Relatív tájékozást
   követően az abszolút tájékozás teszi lehetővé a
   modell-koordináta-rendszerből (ez már térbeli) való áttérést a
   vetületi koordináta-rendszerbe, ahol 7-paraméteres térbeli
   hasonlósági transzformációt alkalmazunk (dX, dY, dZ, dOm, dFi,
   dKappa, m)
7 9.1.  UAV kategóriák: Ezt a kérdést pár ember teljesen kihagyta, de
   a többség jól tudta.

A ZH-t 5 pont alatt javítani kell, az SZ betű a számolás javításának szükségességét jelenti!

Jó szerencsét!

Király Géza

* <2023-09-25 h> Ortofotó
** Ortofotó fogalom
- Ortogonális vetítésű fénykép (ez a készítés, a második)
- Torzulásoktól mentes fénykép (ez a fontos!) mérethelyes fotótérkép is!
** Légifénykép torzulásai
- képdőlés (perspektív torzulás)
- magassági
- objektív elrajzolás
- refrakció
- földgörbület

Ezeket kell kiküszö bölni.

1 képes sík, a kép dőlés, domborzat inkább két képes, magassági.

Kamera a múlt alkalommal.

Utolsó kettő hatása kisebb. Refrakció szintezésnél jelentős. Kólönböző
léghőmérsékletű rétegeknél megtörik a fény. Csillog az
aszfalt. Vízszintes légrétegnél.  Földi fotogammetriánál, vízszintes
tengelynél lehet jelentőssége. Nem foglalkozunk. Jó időjárási körülmények.

Fölgörbület kis méretarányú légifényképnél. Nem sík a
felszín. Manapság ritka.
*** Képdőlés miatti torzulás
Perspektív torzulás Szabályos négyzetrács dőlt tengellyel.
Mindkét tengely dől általános négyzög, egy tengely trapéz.

Párhuzamos egyenesek egy pontba, dőlés mértéke meghatározható.

Egyképesnél ez a cél, hogy ezt kiküszöböljük.

*** Magassági torzulás
Mindig van egy viszonyítási sík. Alatt-fölötte objektumok. Máshová képeződnek.
Magassági torzulás. Fölötte-alatta az épület.

Nem síkra vetítünk. Ami a magasságot is leírja. DDM-re vetítjük. Ezzel
a magassági torzulás kiküszöbölve.

** Ortofotó készítés
- Légifénykép kell egy felvétel, mérőkamera.
- Tájékozás 6 paraméter. Külső tájékozási paraméterek.
- Vetítési (viszonyítási) sík meghatározása. Amire visszavetítjük.

** Centrális–ortogonális vetítés
Vetítési középpont. Centrális vetítésűből ortogonális vetítés.

Valamilyen vetületben készül. Vetület síkjára merőlegesen vetítünk. Minden pontot
a viszonyítási síkra merőlegesen. Térkép-méret helyes.

** Differenciális képátalakítás
Analitikus fotogammetria. Ortoprojektor. Hasonló az analóg képtranszformátorokhoz.
Sztereofotogammetriával magassági vezérlők. Kvázi domborzatmodellje.

Film előtt kis rés, amin át megy a fény. A fotópapírt emelem-süllyesztem a fényképhez.
A vezérlőnél működik.

Kis rés kell hozzá. Digitális fotogammetria pixelről-pixelre.

Kép ferde, ortofotón a szabályos téglalap.

** Ortorektifikáció
Tájékozott kép, ismert tájékozási adatokkal. Képterületen kívül eső, kis pixel és nagy pixel.
Jó áttekintő képhez nagy pixel. Kisebb pixelnek, mint forrás nincs értelme. Nagyobb felbontás nem
szokott lenni.

Pixel közép x,y koordiánáta. Vetítősugár a képközépig. Síknál levetít.

Több kép domborzat alapján ddm, képsík, pixelt lemásolom. Haonló a differenciálishoz.
Alapegységenként a kép helyettesíts. Helyükön a pixelek.

A vetítő sugár általában nem a pixel közepét találja el. Négy pixel közés esik a sugár.

** Újramintavételezés vagy resampling
A pixelekből egy pixel meghatározása.

Három eset:
- Legközelebbi szomszéd :: értékének másolása. Nearest-neighbour.  Vannak
  előnyei pl. gyors. egy pixel olvasni. Hátránya, hogy egyenes vonal
  az eredeti felvételnél lépcsős lesz.
- Bilineáris :: (bilinear) a pixel négy pixel. Eredeti pixel koordiánáta renszer
  két szomszédos pixel lineáris interpolálása, majd alatta fölötte
  lineárisan interpolálok. Négy pixel olvasása. Jellemzően simítja a
  képet. Másodlagos digitális képeknél erős képi zajt simítja. Simítja
  az /éleket/ is.
- Bikubikus :: (cubic convolution) 16 pixelt veszek a
  környékről. Mindkét irányban 4-4 értékem van. A pixelekre 3-ad fokú
  függvényt illesztek. Az eredményre (négy sor) Újra illesztek egy
  függvényt (4 érték) és az oda eső értéket veszem. Képzajt simítja,
  de az éleket nem. Akár jobban is kiemeli az élt. Általában ezt
  alkalmazzuk.

Két féle ábra. Bilineárisnál eredmény szempontjából mindegy, hogy
melyik irányokat használom először. Cubic convulutionnál is
mindegy. Sebsség egyre csökken, de ma már gyorsak a gépek.

** Vetítési (viszonyítási) sík
Mire vetítünk?

Síkra. Síkfotogammetriára. Alföldön tgsz feletti síkra. Homlokzaton a falfelület síkjára
- Sík :: homlokzat, szintsík
- DDM :: dombozratmodell objektum töve lesz jó helye. Talajszintben jó. Ami kiáll dőlni fog.
- BFM :: borított felszín modell. Manapság sokszor a TRUE ortofotót
  készítjük a borított felszín modellre. De van, hogy technológiai
  akadály. Üvegtetőn keresztül lelátunk. Vagy amit látunk (talaj) vagy
  a vázszerkezet. Fák esetén is lelátunk. Csak közelítő
  megoldás. Durva hibák. Ezeknél a konvencionális DDM. Dőlnek az
  objektumok. Töve a jó helyen. Rossz BFM esetén gondok.

Példa. Épület töve letakarja. Ma már inkább true orto. Képegyeztetés,

** Ortofotó-mozaikolás
Légifényképezés több 10 100 akár 1000, ahol nem csak egy kép és
ortofotó, hanem mozaikolni kell.

Sok eljárás:
- Manuális :: korábban vágóvonalakat rajzoltak. (Seam-line) Hol húzza
  az ember. Más helyen, hogy ne lehessen látni út mellett, hogy
  lehessen látni. Szántón, hogy ne zavarjon. Milyen célra készül? Mi
  az igény?
- Automatikus :: Ma már automatikusan készülhetnek a vágóvonalak. Az
  átfedés alapján megadhatom. Kép közepéből mozaikolunk. Kisebb
  torzulások. Kevésbé dőlő épületek. Aut mozaikolás. Korlátokkal,
  kézzel is bele lehet nyúlni.

Példák vonalas, út menti vágóvonal. Nem éles vágás. Lehet átfedő zóna.
Egyik és másik tónus kiegyenlítése. Mindekttő megjelenítve szellemképes.
Nagyon pontos, nagyobb átmenő zónak Pontatlan ortofotó éles vágás is jó.

*** Színkiegyenlítés
ER mapper kép. A vágóvonal jól látható. A kis eltérés, szomszédos
sorok eltérés. Objektum megvilágításában eltérések. BRDF hatás, a
növény a nap felé. Más színe lesz a területnek. Más irányból a
napraforgó más színű.

ER Mapper 1 fotó 25 blokk, pixel átlag statisztika. Igyekszik
igazítani egymáshoz. Próbálja igazítani. Elmehet a statisztika.

Itt fejlesztett eljárás. Szegmensek alapján erdő szegmens. Nem zavar
be. Szegmens egyeztetés.

Ez lett volna az ortofotó mozaikolás.

** Képegyeztetés
Sztereo fotogammetria. Amikor az átfedő képeknek egyes részeit
megpróbálja a szomszédos képekkel egyeztetni. Automatikus mérések.

- Relatív tájékozás :: Ennél is használható. Automatikusa
- Objektum rekonsturkció :: térbeli mérések a segítségével.
- Sok egyéb ::

*** Sok eljárás
Gyorsan fejlődnek, újabb és újabb eljárások. Maguk korlátai.

- Területalapú
- Objektum :: 
- Kapcsolat :: 

**** Területalapú
Minta alablak, mozgó ablak. Kereszt-korrelációval.
Legkisebb négyzetek elve is jó.

Félelmetes képlet, de nem vészes. 3x3-as ablak.
eltérés - 9 pixel átlag

Másik ablak is átlagtól való eltérés szrozat összege.
Átlagos eltérés négyzetösszegével elosztom. Egy-az-egyben a képrészlet.

Ugyan az a képrészlet mások a pixel értékek. Ugyan-úgy egyet ad a kép.
X,Y pozícióban a korreláció.

***** Legkisebb négyzetek
Sokszor épülhet a ccf-re. Sokszor nem! pixel értékek különbség.

Geometriai eltérések affin trafóval a legjobb.

- 1983 Ackermann cikk. Ez volt az első.
- 1988 Grün–Batsavias. multiphoto matching. Nem csak képpárok, tíf
  fotót egyeztetjük. Nagyobb megbízhatóság.
- 1988 Helava híres műszere is volt. object space least sq. képsíkon
  és térben is! Van pro kontra a képsíkon és tárgytérben
  egyeztetésnek. Z irányban is mozgatni az ablakot. Tér magasabb
  számítás, jobb eredmény.

Innen folytatjuk.

**** Objektum
**** Kapcsolat

* <2023-09-27 sze> gyakorlat
Jövő héten talán a GT-ben leszünk. Jó lenne átmenni. Egy ideig leszünk csak el itt.

Kapcsolópontokkal a relatív tájékozás megvolt.

Raszter menüpont, tömbkiegyenlítés.

G:\TopoXmap mappából futtatni a programot.

Raszter- tömbkiegyenlítés pontja.

Projekt megnyit

M:\Foto 2003 Király

Keretjelek.

Újra adott forrással sem nyílik meg.

ecw dll-ek változhattak.

topolynx.hu

Valami gond volt a telepítéssel.

23.4.11-i program.

Fálj megnyitási hiba! Ha környezeti változó nincs megfelelően definiálva.
M-ről az állomány.

Kép tervezés menü. Egymáshoz képest beállítani a menüből. Kapcsolópontok pontosítandók.

TopoXmap nem oldja meg a relatív tájékozást a kapcsolópontokkal. Csak az abszolút tájékozással.

Ehhez illesztőpontok kellenek.

Új térképnézet. Hozzáadni a G:\topo\ könyvtárból az eov10 sopron ecw állományt.

** Illesztőpontok
Képen és térképen is (valóságban is) tudunk azonosítani. Terepi (GNSS) méréssel határozzuk meg.
IP
IP1 px py EOV_Y EOV_X EOV_Z

Illesztőpont fül-nél a valós koordináták.

N = nagyít a teljes nézetre.

Hány illesztőpontra van szükség az abszolút tájékozáshoz.

Van egy térmodell, amit EOV-ba kell tájékozni. Eltolni, beforgatni és méretarányát meghatározni.
7 paraméteres trafo. Geodéziában hasznélt.

- 1 pont eltol, másik pont eltol és forgat, 3. pont a harmadik szög. 2
  pontot összekötő egyenes körül még billegtethetem a modellt.

Teljes tömb 3 illesztőpont. 3 illesztőpont elég az egész tömbre.

Szeretjük a fölös mérést.

5 illesztőpontot próbálunk megmérni. Minél inkább a képek sarkaiba legyenek a pontok.

Szélső képek szélén legyen 4, egyet középre.

1020 ágfalvi rész.

** Illesztőpont lerakása
Ctrl és kattintunk a térképnézeten. Automatikusan létrehoz egy pontot.

Hozzáad, akkor 0,0 és kapcsolópont, ip-re az ikonnal átkattint és utána az aktuális
és utána adom meg a koordinátáját.

Ctrl-nyomva kattintok a térképen kattintásokat spórolok.

5 illesztőpont keleti és nyugati felére. Térképen nincs Ausztria. 5. pont Botanikus kert.

Töröllel az aktuális pontot törölhetjük.

Kiválasztom a listából, majd a térképen kattintok, s odább teszi a térképen.

Új koordináták ciánkékkel jelöltek. Térképen, a sárga pontok a fényképeken.

Más szóval az illesztőpontoknak EOV koordinátái kell, hogy legyenek.

Ha leraktuk a pontokat, utána a képeken is le kell rakni.

** IP mérés

IP mérés ablakból
Hozzáad és a megfelelő pontszámmal lerakom a térképen lerakottak párját.

14-es pont mind a két képen! Mert középen.

Három mérés az új illesztőpontokra.

Projekt fülre visszamenve mentsünk!!!!

Pontosítás méretaránnyal 1:20000-el kezdjünk.

Képen bal klikkel módosítom, térképen jobb klikkel az IP méréssel.

Dupla kattal középre. Nem azonos a méretaránya. Egy pixel 1 m akkor lenne azonos!

Illesztőpontban duplán rákattint, akkor behozza.
IP mérésben duplán kattint akkor középre.


Illesztőpontoknál kattintok, hogy az összes képen behozza!

** IP egyesével végig menni.
- Mukki őrs, Éles határ.
- Ikva híd,
- Kőfejtő,

** Közös, két képen lévő illesztőpont
Minden képet megnyitja, ha duplán kezdünk.

Az az erzsébetkert sarki ponthoz.

Épületek nem olyan pontosak a topo térképen, mint az utak és vasutak.

Út tengely metszés biztosabb, mint épület sarka.

** Átnézés
Megnézni, hogy minden rendben.

Projekt ment

Majd a kiegyenlítésre kattintani. Kiegyenlítés után felrakja a kapcsolópontokat,
de addig nem.

Légi háromszögeléssel új pontok koordinátáit is meg tudjuk határozni.

IP és KP is haszált Vannak köztes pontok S = síkbeli pont.

** Síkbeli pont
TV torony
Alsó pötty.

Ctrl katt. 180 a torony magassága.

Síkbeli pont nem veszi figyelembe a magasságát.

Tövét nem ,de a csúcsát könnyű megirányozni. Síkbeli pont lesz.

** Magassági pont
Ahol van egy tavunk. Van rajta bólya, tudom a tó szintjét, de nem tudom, hogy hol a bólya.

Nem ismerem a pontos helyzetét.

** Kapcsolópont
Ő határozza meg mind a három koordinátát.

** Méretarány nagyobbra veszem
1:20 000 helyett 1:4000

Tengely metszés tapasztalatok szerint kisebb hiba!

** Illesztőpont magassága

Eddig a pontjainknak mem adtunk magasságot!

Digitális domborzatmodellből be lehet tölteni magasságot.

Hozzáad a G:\dfotogr\ddm10soproners
G ddm-ből adtam hozzá az erst.

A térképnézethez hozzáadni!

Illesztőpont xy toporól, z-t pedig ddmről

Projekt Terepmodellben beállít  terepmodellt
Odébb teszem, akkor jó, vagy számít.

Számít, vagy mozgatva.

Sík pontnál

Projekt ment kiegyenlít.

100-as hiba közelítő megoldás.

1000 durva hiba

10 jó!

** Kiegyenlítés után
ISSK állomány a projektnél

Képeknél omega, phi kappa cy...

Felírja

Tervezésnél is lehet látni.

** Tavalyi anyag alapján
y: meghajtóról

4812 m

4858 Z centrum koordináták abszolút érték. lejön a terepmagasság relatív magasság.

** Kiegyenlítés nézése

Utolsó aktuális mappába menti.
points és lines kezdetű (bna?) fájlok.

Projektból megnyitjuk a bba állományt újra, s az marad az
aktuális könyvtár. Mentésnél a kiegyenlítés már oda teszi.

BNA boundary atlasz pontok vonalak és poligonok.

Térkép import, points és lines beimportálás.

Foto képközéppontból mérek.

A térképen osztályozni kell ATLAS2 alapján.

A térkép osztályozba beírni.

Felirat ATLAS1 alapján a pontokon. Felirat mérete 5 mm
Dupláz vagy hozzáad újra.

És alul egy mező a feliratnak.

z közel megyegyezik omega phi nulla körüüli
\kappa az adat

** A kétképes kicsit félre téve másik tájékozás
Projekt új és leírásnál 2008 

X meghajtó becsatolása

gevinas2\geoc

Y = munkac

X: dfotogr 2008 ecw

** Kamerát definiálni
2014-ben milyen kamerával repültek?

UltraCamX

lechner légifelvéelekről

Kamera Vexcel UltaCamX

Tavaly QGIS a fejlécben y: Gy05.txt

c = 100.5
*** képfőpont
0 0.216
*** Képméret a kameránál
Képméret és a keretjel koordináták

Kamera értékei 

67.824/2

0.0072 felbontás
Kép pixel méret és felbontás.

(14430 * 0.0072) / 2 # 51.948
(9420 * 0.0072) / 2 # 33.912
** Keretjel
Beállítani a képeknél a kamerát (most utólag csináltuk)

És alaphelyzetet választani.

Itt nem kell a keretjelet mérni, hanem a fenti számolással megy a belső tájékozás.
** Tervezés
Kép tervezés gomb.

Másodlagos képeknél is használhattuk volna a másik módot.

x dfotogr 2008-ban

csv állomány minden képhez

képszám xext, Yext Zext

Ph_grd 400-as fok!

Kappa 200 körüli!

Adatok átváltása!

2856 sor kimásolva. Excelbe betéve.

Adatok szövegből oszlopok, ponotsvessző a határoló.

Tizedespont van, tizedes vesszőre cseréljük! Számként értelmezni.

Újfok rendes fokba

Külső tájékozási adatok a képpel együtt letölthetők. Mindegyik et átváltom.

Osztani 400 és szorozni 360-al.

Kappának 180 fok körülinek kellene lennie!

Ezekre, mint közelítő tájékozási adatokra lenne szükség.

Lemásol és beteszem egy állományba. Vesszőket pontokká cserélem.

X: dfotogr 2008 centrum V0-ba mentette.

Kép esetében beírom.

Tervezés jobb klikk centrum betöltés

A teljes szövegre kiegészítített.

Egy képet nézünk

Balra van észak. Hány fokos forgatási szög

-270 vagy 90-re kellene állni!

Minden szögből méglevonni 90 fokot.

Átírva, újra betöltve. A tervezés centrum betöltésnél!

** Kötőpont arréb
Rá kell menni az iránytűre!

Tervezésben 9 kötőpont/képre kattintani.

Nagyjából jól elhelyezve 1:10 000-ben nagyjából jó

Akkor jó a kapcsoló pont, ha biztosan azonosítható, de kisebb objektum.

Az első néhányat sikerült megcsinálnom.

* <2023-10-02 h> Képegyeztetés folyt.
** Képegyeztetési eljárások

*** Területalapú
Múlt órán volt
*** Objektum
Feature-based matching

Bármely eljárással pontokat, vonalakat területeken keresünk, s ezeket próbáljuk egyeztetni a képeken.

Operátorokkal tudjuk detektánlin (kb. szűrő eljárás)
- Moravec
- Förstner
- Haris

Kicsit bonyolultabb, mint egy sima szűrő.

Detektált objektumok azonosítása az átfedő területeken.

**** Förstner
Förstner (1987) A fast operator for detection and precise location of distinct points, corners and centers of circular featrues. 

Ma is használják és gyors.


*** Kapcsolat
Relation-based matching

Wosselman and Haala (1992) Erkennung topographischer Passpunkte

Pontok kapcsolat alapján.

Wang (1995) A New Method

epipoláris geometriát felhasználja a kapcsolat keresésénél. Geometriai kapcsolatot felhasználva
találja meg a pontokat. Objektum rekonstrukcióhoz.

Különböző szoftverekben, különböző képegyeztetési eljárások.

*** Mai leggyakoribb
- Semi-global matching (SGM)
- Structure from Motion (SfM)

Ezek az aktuálisak, de lehet hogy holnap jön az új és hatékony.

**** Semi-Global Matching
Hirschmüller (2005 és 2008)

Lokális korreláció az adott ablaknak párja.

Globális képegyeztetés a kép egészét nézi. Sokkal robosztusabb és hatékonyabb,
de iszonyú számításigényes, lassan futott le.

A lényege sikeresen ötvözi a globális és lokális szereó képegyeztetést, pontos,
akár pixel szintű eredményeket kisebb száítási igény mellett produkál. Óriási siker volt.

Alapja az optimalizálási feladat költség-funkció alapú. Úttól távol a szálítási költségek
legalacsonyabb-legmagasabb költségek. Nagyon felgyorsítja az eljárást. Globálisan olyan megoldása
volt, nem kellett a képre lefuttatni.

Sok cikke jelent meg. Hirschmüller (2005), 2008, 2012, 2013-tól elérhető a Daimler Mercedes autókban.
Olyan chipek vannak, amelyek hardveresen csinálják. A kocsiban sztereo kamera.

Mercedes vezetéstámogatás 6D-Vision Régóta foglalkoztatta a gépjármű tervezőket.
Sztereo kamera pár alapján a mélységet lehet látni. Kalibrálást meg kell ismételni időről-időre.
xilinx FPGAra készített megoldás. Elég-e a 3D? 6D minden időpollanatbn nézik a 3d térképet. Objektumok
sebesség vektorát próbálják elkapni. Kalmán szűrőt használják ők is.

Sebesség vektort is rögtön becslik. Jellemzően a visszapillantó tükör modulba építik be. 50 km/h-ig
gyalogos elütés. Dugóban vezetés automatikus. Rossz idő lateral and longitudinal control menettulajdonság hangolása.

2013-ban nagy durranás. Manapság már majdnem minden autóban vezetéstámogató rendszer. Aktív (radar), lézer, passzív
eljárások. Kettő kegészítés. Esőben lézer, párában optikai... Több szernzor jobb. Ultrahang radar. hosszabb-rövidebb hatótávolságú.

Kis bázis 500 méter mégis. 45 fokos látószög. Éjszaka is alkalmas, írják. Gyalogos osztályozás és merre mozdul.
2 millió példa az adatbázisban. Online a felhőben és példák alapján tanul.

Még hatékonyabb. Voxelek sztere pixelek = Stixel.

LIDAR összehasonlítása. Veoldine szkenner. 16, 32, 64 fix pászta. körbeforog. Azzal hasonlítják össze.
Előnye, hátránya. Urban environment.


***** Autóiparon kívüli alkalmazások
Törésvizsgálatokban nagy szerep. Gyors folyamatok, megfelelő detektálás
Törés teszt jelek nélkül.

Robotika.

Újabb drónoknál ütközés gátlók Obstacle avoidance system. Sztereó kamerák fölfele-lefele.
Iszonyű nagy fejlődés. Ütközés elkerülő is ilyet használ.

A Mercédesszel kezdődött. Sok autóban ott a tükörnél a sztereo kamera.

**** SfM Structure from Motion
Régen felfedezett alapelvek, de sokat kellett rajta dolgozni.

Maga a szenzor, ami képet csinál mozgásban van. Ez alapján csinálja a képegyeztetétst. A szenzor elmozdulását is becsli.

- Képsorozat
- Elmozdulás

Potenciális kapcsolópontok felkeresése a SIFT algoritmussal (Scale Invariant FeaTures) 1999

Durva hibák szűrése RANSC algoritmus (Random Sample Consensus) véletlen mintasorozat, durva hibák
kombinatoriailag kijönnek.

Egy lépésben meghatározza a szenzor pozícióját és a relatív tájékozását.

Ullman 1979-es cikke az alapja (Interpretation of strucutre from motion.

Förstner (1986) is fontos a megoldáshoz.

Remondino és El-Hakim Image-based 3-D modelling: a review. 2006

Eredeti elképzelés a közösségi médiába feltöltött képek turisztikai látványosság.
A sok képből a 3D modell pl. Tűztoronyra megcsinálható. Meg kellett oldani, hogy a
kameraparaméterek általában ismeretlenek. Olyan kamerák alapján 3D rekonstrukció,
amelyek behoznak egy csomó ismeretlent!

Snavely 2008 továbbfejlesztette. Scene reconstruciton and visualization from Internet photo

Volt microsoft 3D modellező is.

Verhoeven, Doneus, Briese Vermeulen (2012) Holland és TU Wien.
Oroszok továbbfejlesztették, de nem dokumentálták rendesen. Ők segítettek
az oroszoknak és összefoglalták a lépéseket.

Westo by, Brasington, Glasser, Hambrey Reynolds (2012) SfM photogammetry.

Olyan képegyeztetés pixel szintű és nagyon részletes. Jelentősen megváltoztatta a digitális fotogammetriát.
Ma nem is igazán tudjuk, hogy melyik használja.

Gyakorlaton SfM-el kicsit részletesebben megismerkedünk.

Egyik napról a másikra új eljárások jöhetnek.

** Lézeres letapogatás (Laser Scanning)
A két pontfelhő eltérő, mint a képegyeztetésből.
Lézeres letapogatással megismerkedünk. Utána fogjuk igazán összehasonlítani.

*** Aktív érzékelő
Fontos különbség!

- Nem képalkotók
  - távmérő
  - altimeter
  - scatterometer (szórásmérő
- Képalkotó
  - LIDAR
  - RADAR

**** RADAR Radio Detection and Ranging

- Időjárás független véda kapu esőben is lát.
- Napszak független
- \labda = 1-100 cm

**** LIDAR
Light Detection and Ranging

- Napszakfüggetlen (nem időjárás!!!)
- \lambda = 400-1700 mm

Ködös időben a vízcseppekről, esőben esőcseppekről verődik vissza.

Mindegy, hogy éjjel vagy nappal, de vannak LIDAR szenzorok, amiket a túl erős napsütés
befolyásol. Háttérsugárzás.

*** LIDAR
- Optikai tartományban
- Távmérések sorozata

Időben elhúzódó és letapogat a képhez

*** Lézeres letapogatás
Hordozó eszközök:
- Földi
  - statikus szkenner, a műszer állványon
  - külön mobil hordozó eszköz
- Légi
- Űr

*** Módszerek
Különböző eljárások. Időben változnak. Egy eljárás felkapják, jön egy újabb még jobb.

**** Háromszögelés
Mintázatot vetítenek ki. Sztereó kamerával figyeljük a mintázat paralaxisait

Folyamatos hullám alkalmazása a távolságméréshez. Nem impulzusok.
Fontos különbség, hogy folyamatos hullám gyorsabb. Sokkal nagyobb
számolási igényű is! Fázis többértelműség, több utas terjedés itt is zajt ad!
DE sokkal nagyobb sebesség!

Impulzus alapú > 10 m

Háromszögelés MS Xbox Kinect
100 ezres kiegészítő a TV tetejére. Földmérési alkalmazás. Olcsó szenzor.
Játék ipar mennyiség más! 20 millió helyett 100 e Ft.

Ugyan úgy mintázatot vetít ki infravörös fénnyel. Két kamerával figyeli a mintázat
görbüléseit. Méylség kép valós időben. Mozgás fontos. Kb. 40 cm-es bázis vagy kicsit kisebb.

Játékfejlesztők kaptak SDKt pontfelhőt kivették belőle.

Mintázat kivetítése. Képeket mutatott.

**** Folyamatos hullám
Majd visszatérünk. Nem volt jó a képlet kivetítése.

**** Impulzus alapú távmérés
c=3*10^8 m/s

1 m 3.33 ns tesz meg a foton. Nagy felbontású időmérés.

Oda-vissza megy fele kell!

3 ns felbontás kb. fél m! pico sec mérés.

1 mm = 3.33 pico sec

Egy egy impulzus. különböző módon modulált. Téglalap vagy más alakú jelek.

R = 1/2 c * \delta t

Fontos a fázis meghatározása. Hullámhosszon belül tudjam, hogy merre. Hullámhosszon belüli
távolságok. Kódmérés és fázismérés a nagyobb pontosságért, mint GNSS-ben!

**** Single Photon LiDAR
Újabb technológiák.
Egy-egy fotont érzékelünk. Űr lézerszkenner esetén nagyon fontos!
NASA Miroaltimeter (2001) ISAT2 műholdhoz ezt fejlesztették tovább.
Több újdonság

**** Geiger Mode LiDAR
Geiger-Müller számlálóhoz hasonló 

Military, Harris IntelliEarth

Nem forgalmazzák. Meg lehet rendelni, nem forgalmazzák. katonai kitelepülés, de nagyon gyors.

**** Multispektral LIDAR
3 különböző hullámhosszú laser, Különböző hullámhosszon tudja a reflektanciát.

Zöld, közeli infravörös laser több is lehet! Közvetlen színinformáció. Zöld zöldből jobb a visszaveerés.

Csak részben látható. Hamis színezésre alklamas. Tengerparti területeknél nagy jelentőség. Vízbe bemegy az
egyik, a másik a felszínről verődik vissza. Vannak gyártók, akik ilyenre rámentek.

Optech cég volt az első.

Mindig is vannak és lesznek új technológiák.

IPHONE 13 pro TIME OF FLIGHT kamera. Be van építve a szenzor a készülékbe.
Komoly dolgokat 2013 pro kiadástól jelentek meg! Mélységi kamera.

Lehet, hogy lecsökken.

** ZH
Kinek nem jó a számolás.

Nem akarunk foglalkozni. Még egy ZH az alapfogalmakból lesz. Arra számítani. Számolást 2. zh alkalmával pótolni.

* <2023-10-04 sze> Gyak folytat
Szenátus miatt sokat késtem.


** 1. Ortofotó

** 2. DDM

** 3. kimenet
Korrigálják az épületet.

Részletmérés

Pontokat vonallal összekötik. Tető struktúrát megrajzolják.

Bal klikk és jobbal lezárom.

Meglévő pontokat, 3d koordinátát tudja.

Kémény vagy másik tető.

Elmenti txt-be. Sok EOV koordináta.

Térképként a másk formátumba, nem szövegfájlba, hanem dxf állományba. 19910061tmKalicz.dxf
Ezt a dxf állományt megnézni autocadben.

Rasztertranszformáció megy közben!

Puritán dxf. Nincs benne a fejlécben a terjedelem. Ránagyítva az RK-ra.

3D tető! Az RK mérése alapján! 3D adatok.

** Összegzés
Korábban ez volt a kiértékelés lényege.

Sztereo szemüveggel nézték. Mi változott és mi nem az adott területen?

** Elsődleges képek
Még a tájékozás nincs befejezve. UltraCamX keretjelek a sarokban.

Illesztőpont nem volt, csak kapcsolópontok.
Dupla klikkel a három képet.

BazsóKalicz-t folytattam.

*** Illesztőpontok
3 kép 5 illesztő pont. Sarokra és középre.

Ctrl-el automatikusan ip

DDM10 betöltve. Nem kell külön z koordináta.

3 kép és egy térkép

*** IP mérés

Lerakosgatjuk. Mivel lehet arréb rakni. Jobb gombbal.

Magas hiba.

Tervezés a szélső kép nagyon el van ferdülve.

Ha gond új illesztőpontot letenni. Mennyire jó?

Z koordináták jól illeszkednek.
\kappa-val nem kell foglalkozni.

points és lines mindig fölülírva. Térképnézeten hogyan néznek ki?
Újból be kell importálni. Ugyan úgy mint a másiknál.

points2008 névvel máshogy!

Képkeretet 23*23-ast írja ki. Igen nagy. Nem jók!

Trafó 20%, így óra végére sem lesz meg!

*** Elsődleges kép méricskélés
Bázis magasság viszony. Két képközéppont távolsága
1885 m a képközéppontok távolsága. Bázis/magasság viszony.

*** Kettő összehasonlítása
**** Elsődleges
Bázis = 1885 m
H = 7110 m

B/H = 0,265

**** Másodlagos
B = 2600 m
H = 4630 m

B/H = 0.562

Több mint duplája. Bázis magasság viszony.

Térbeli mérések vonalai nagyobb szögben metszik egymást.
Nagyobb bázis magasság viszony pontosabb magasság mérés.
Szomszédos képek között nagyobb eltérés.

DE a képegyeztető eljárások a kisebbnél jobban működnek.

Katonák iszonyú nagy látoszög. Szinte derékszög. De képegyeztetés nem megy.

Még a 3. szomszéd is mérhető. Sokat csattogtantunk.

Közbe leállt.
**** Úra 2008.
Másik részletmérését betöltjük.

Elsődlegesbe betölteni a másodlagost. Szistematikus eltolódás.

** Házi
Előző félévben választott elsődleges és másodlagos képet folytatni!!!

* <2023-10-09 h> Ea.
Múlt alkalommal lézeres letapogatást kezdtük el.

** Elve
Távolságmérések nagy frekvenciával. A kibocsátott impulzusokhoz szögek
és távmérések. Koordináták külső tájékozási adatait ismerjük (GNSS/INS)
Eredmény 3D pontfelhő. Szögek és távolságok koordináta különbség meghatározhatól.

Koordináta a fentiből. Eredmény 3D pontfelhő.

Time of light szkennerek idő alapon

** Full waveform
1 kibocsátott impulzus, egy visszaverődés.

Még az egyszerű távmérőknél is benne, hogy legtávolabbi
vagy legközelebbi távolságot. Gyakori lett az első és utolsó impulzus.
First/Last.

Utána ahogy halad a technológia 4–6 visszaverődés.

Ebből jött a full Waveform. A teljes visszavert jelet digitalizálja.
A visszavert jel digitalizálásának sok előnye. Diszkrét visszaverődések.

Előnye: Több információ, infó az adott objektumról.

Nagyon kicsi szöggel kibocsátott impulzus (ez is IFOW). Kúpot világít meg.
Minél közelebb, annál kisebb (kör = merőlegesről, ellipszis = ferde).

Visszavert jel alakja alapján el lehet különíteni, hogy milyen objektumról
verődött vissza az impulzust. A 3D pontfelhő struktúrálatlan. Jól jöhet minden
eltárolt információ!

Így pl lapos/nem-lapos tető elkülönítés. echo vic???

Vannak olyan szkennerek. Digitalizálja, és meghatározza a diszkrét visszaveerődéseket.
Gauss görbék szuperpozíciója. Ahová illeszti az lesz a távolság számítás alapja.

- konkrét visszaverődést elteszi, s utólag feldolgozza. Komplex esetben sok visszaverődés.
  nincs völgy a két csúcs között. Több Gauss-görbe egymáson. Sok szkenner esetén megvan,
  hogy egy impulzusból milyen távolságot tud elkülöníteni.
- Más szkenner nem rakja ki.

Ma legtöbb a full-waveform-ot használja. Csak akkor, ha komplex a terület.

** Alkalmazási területei
*** Topográfiai felmérés
Ez volt az alap. 80-as években jelentek meg, de nem volt pozícionáló és inerciális nav. renszer.
A pontfelhő nagyon pontatlan lett.

90-es években jelentek meg a már pontosabb szkennerek.

Ma már ebben nincs alternatívája. Olyan részletes adatsor, ami más technológiával nem.
*** Városi modellezés
Város modellezése. Széleskörű alkalmazás
*** Régészet
Fontos alkalmazás. Nagy előnye a fotogammetriai felmérésekhez képest,
hogy behatol a növényzetbe. Növényzet alatti felmérés.  Utak, sáncok,
halomsírok jól látszanak erdő alatt is!

Amíg egy szántón a művelési munka el erodálja a régészeti
leleteket. Erdő alatt ritkább a művelés. Jobban megőrzi a felszíni
formákat.

Pár éve egy híres lelőhely dél-amerikában környékét felmérték. Kétszer
akkora a város, mint gondolták. Növényzet alatt is kimutatta.
*** Közlekedés
Vonalas létesítményeknél felmérés, tervezés, bővítés, akár forgalomszámlálásra is!
Műegyetemen foglalkoztak Magyarországon először!
*** Erdésezt
Akár lombos állapotban domborzatmodell. Famagasságot segítségével nagy
pontossággal mérhetjük.

A topotérképek régi térkép magassági adatainak
átvételével. Fotogammetriai úton pontosították.  Fenyő alatt nem
tudtak magasságot mérni. Tényleges domborzat és DDM5 30 m-es eltérés!

Erdészet utolsó visszaverődésből terepmodell meghatározása.
DDM magyarul a terepfelszínen. Terep magasságot leíró.

Első visszaverődés digitális borított felszínmodell.

A fenti kettőből magasság.

Lombos állományról kevés pont télen a lombról. Nyáron a lombkoronán
keresztül alig jut le, közöttük jól lelát.

Fenyőnél is azért télen kevesebb a visszaverődés a lombról.

Egyes fák osztályozása.

*** Sok egyéb
Még sok minden. Sok helyen használják.

Nekünk topográfia az elsődleges.

** Működés
/Riegl LMS-Z420i/ működése.

Eddigi alkalmazások légi hordozó eszközökre vonatkoztak. A fenti lézer szkenner földi.

(Űr, légi, földi). Földinél mobil vagy statikus! Fontos!

Régi típus. Ez, amit először használtak (2005 vagy 2006). Riegl osztrák cég. Alsó-Ausztriai gyár.
A top ban (első 3) benne vannak. Ezen keresztül a felmérés.

Elektronika–impulzusok forgó vagy oszcilláló tükör, prizma kerül kibocsátásra. Fej forog, ami
a vízszintes forgás. Csigavonalat ír le körbe-körbe.

Ez ethernettel kapcsolódott terepi számítógéppel. Ez vezérelte az eszközt. A pontfelhő színezésére
fényképet használ. Külpontos képek, de közeli objektumoknál gond csak. Ma is van, ahol külpontos kép
készül. Másik csatoló a fényképezőt köti.

*** Fontos paraméterek
- Frekvencia : 8kHz (ma már 4MHz)
- Hatótáv 2–1000m (A maximum az izgalmas ez még ma is jó!) Felület reflektanciájával adják meg, hogy a felület minőségétől. 90 és 10 %-os reflektanciánál.
- Hullámhossz: NIR – más-más lehet. Általában a közeli infravörös (NIR) ebben is több hullámhossz. Van vörös (mint egyszerű távmérőben, és van zöld is).
- Lézer divergenciája: 0.25 mrad vagy 25 mm/ 100m – Amivel megvilágítja a szöget
- Szögfelbontás: 0.0025/0.002 fok
- Szögtartomány: 360fok/80fok A teljes gömböt szkennelni képes.
- pontosság 10 mm
- súly 14.5 kg

*** Minta szkennelés
Bemutatta a 3D pontfelhőt. Fa árnyéka, ahol nincs információ. Nap árnyéka is a színezésben!
A lézer visszaveerődik a vékony ágról, de a kép már nem látja. Vagy a szél elfújja az ágat.

Gyakorlaton majd látjuk, hogy metrikus és pontos felhő. Bármely két pont és a kettő távolsága mérhető.
NEM STRUKTÚRÁLT! nem tudja a pontfelhő, hogy mi-micsoda. Fontos lépés, hogy leválogassuk a tereppontokat,
utána elkülönítjük a tereptárgyakat, majd tovább modellezzük a fákat. Pontfelhő, de jelentős feldolgozás után
lesz belőle modell.

Leválogat, szeletekre idomokat, objetum, utána az objektumról doglozunk.

** Légi szkenner
TopoSys cég Falcon II. szkenner
- Hatótáv 1600 m
- Távolság felbontása 1.95 cm Stopper óra milyen időközönként mér.
- Kesteny pászta 14 .3 fok
- Letapogatás frekvenciája 653 H7
- Lézer freq 83 000 Hz
- Hullámhossz 1560 nm
- Adatrögzítés: First és Last és Intensity: visszaverődő jel erőssége.

Különleges elrendezés tükör pálmalevél szerű üvegszálas optikába irányítsuk. És mozgatták.
Referencia jel (duplex jel) közvetlenül visszavezetik a jelet a detektorba.

Két átfedő repülési sáv. Szinuszok egymáson pontokból. Szakadás benne. Szabálytalan pontokból
szabályos modelleket. Mo. első letapogatás. Sarród 17 km^2 100 mio pont 6 pont/m^2

2004-ben nagy kihívás volt.

First/last ból modell. Utolsó visszaveerődés visszajut. Első közbeszerzés nem lett sikeres,
de augusztusban is jelentősen megvoltak a tereppontok.

Pontosság: vsz jobb mint 0.5, magassgái 15 cm

Ma is kb ennek lehet hinni. Precíz műszer 20 cm!

Magassági jobb, mint vsz-es!

Párhuzamos GNNS mérés! Saját bázis! Autó és pont kijön.

** Űr szkennelések
ICESat volt az első. 

Jég-, felhő és föld-magasság mérő műhold. Globális modellben a sarki
jégtakaró mennyiségének meghatározása.
2003–2009-ig ment.

EOS program része volt.

590 km magasan keringett! Távolságmérés!
94 inklináció.

Közel kör alakú fagyott pálya.

Évente 2* ugyan azon a pályán mért. Profilok mentén. 15 km egyenlítőn (magyar 9 km!)

Szenzor GLAS Geoscience Laser Altimeter System

Két frekvenciás 532 nm 1064 nm

40 Hz

70 m lábnoym 170 m-enként.

Nagy pontosságú GPS és csillagmegfigyelés.

Felhőt is mért, jeget is és szárazföldön is mért.

Pl. Globális erdő magassági térkép!

*** ICESat-2
Sokat csúszott.
2018 szept.
Más lézeres berendezés ATLAS Advanced Topographic Laser Altimeter System

Zöld lézer 532 nm

Pár erős és gyenge lézer dinamikai tartomány növelése. Különböző reflektivitás.

10 kHz
800 ps stopperrel probléma volt.

Földön Erős és gyengébb 3.3 km, 2.5 km profil mentén! Helyi lejtőt is meg tudják mérni
Pásztára merőlegesen. Fel és leszálló ág, kereszt vonal.

Sok helyen (Open Altimetry oldla)

Ingyenes letölthető terep és BFM magasság.

*** Copernicus Sentinel-6
20220 nov 20

Tengerszint változás. Posseidon és Jason küldetések továbbvitele.

1993-óta óceánok 3mm/év emelkedést mutatnak

*** Gedi
GEDI egy lézeres berendezés. The Global Ecosystem Dynamics Investigation
A nemzetközi űrállomáson.

25 m a megvilágított, teljes jel alakot rögzít. Ferde pályán van, sarkokat nem
érzi, de növényzet magassági profiljára jó. Sűrű növényzet több foton.

2018 decembertől. 51.6fok pályahajláls 51.6N. Sarki területek kimaradnak.

GEDI Forest Canopy Height

Eddig az oroszok húzták, de még nincs technológia Elon Musk.

Orosz-Ukrán háború a rakéta technológiában gond. Még amcsikhoz is oroszok
szállítottak hajtóanyagot.

https://gedi.umd.edu

A fenti három az űr letapogatás.

Jövőre lézeres letapogatás, feldoglozás és pontfelhő összehasonlítás.

* Mi-hol
G:\TopoX program
M:\Fogo22023\KaliczP átmásoltam a gyakorlat végén.

Raszter/Tömbkiegyenlítés

ECW 3-as. 500 MB-ig ingyenes. ECW compressor. DLL-t is le lehet.
500 MB-ig ki is írhatod.

KP arréb rak bal gombbal mérésnél.
