#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:nil broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Fotogammetria 2.
#+date: 2023
#+author: Kalicz Péter
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3)
#+latex_class: article
#+latex_class_options:
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[hungarian]{babel}
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex

* Kezdés
08:15-től kezdenénk

* Szervezési kérdések
Péter tavaly véletlenül régit vett fel.

Vizsgával elmaradtak páran. CV-s vizsgát meg kell
csinálni annak, aki folytatni akarja.

Feladatokkal kapcsolatos elmaradások. 1 héten belül pótolni.

Meher, Evelin, Szendery Gergely. Mi is!

* Anyag
Az első féléveset folytatjuk. Mindenkinek megvannak
az alapfogalmak. Érdemes átismételni.

2 db ZH a félév során. Az első a tavalyi anyagról is
szól. Áttekinteni az alapfogalmakat.

Korrábbi google drivet OneDrivera cseréljük.

* Ismétlés
** Foglalma
Fotogammetria. Fényképmérés, mennyiségi információ szerzés
a tárgyakról objektumokról, fénykép készítés és kiértékelés.
Képek és objektumok közötti matematikai kapcsolat. Centrális
vetítés tulajdonságai alapján.
** Felosztás
Eszköz: űr, légi, földi, eszközök mozgásban vannak így hordozó
eszköz alapján

Média: fotográfiai rendszerek, digitális érzékelővel.
Analóg és digitális képek.

Kiértékelés:
- Analóg :: analóg képekkel, analóg módszerrel optikai, mechanikai eszközök.
  nem kell számítás. Grafikus kiértékelés
- Analitikis :: analóg -> digitális. Analóg képekkel, számítással tárgykoordinátákat.
  Műszeerei a mérő mikroszkópok, vagy komparátorok, képi koordinátát mérünk, meghatározunk.
- digitális. Digitális -> digitális. Analitikushoz közel. Képi
  koordináta helyett pixel koordinátákat mérünk, amelyeket képi
  koordinátává alakítunk. Sok lépést automatizálhatóvá tesz. Korábban
  rengeteg emberi munka. Ez akár teljesen automatikus munkafolyamta.

Milyen koordinátát kapunk:
Centrális vetítés 1 kép x,y koordináta csak z függvényében.
Megadott síkra vetítve.

Ha mindhárom koordináta, sztereo fotogammetria. Ma inkább
több képes fotogammetria. Ma ez a jellemző.

** Centrális vetítés
Legfontosabb tulajdonságai.
- Egyenes képe egyenes
- Hasonlóság kizárólag akkor van, ha a tárgysík és a
  képsík párhuzamos


Alapvető számítások
Kép méretaránya = képen mért távolság/terepi távolság
M_k = c / h_0

h_0 = c/M_k

c = M_k * h_0

Gyakorlatban méretarányszám
M_k = c/ h_0 = 1/A_k

A_k = h_0/c 

Bázis és sortávolság

B = s * (1-p)

A = s * (1-q)

** Fényképezési felvevőrendszer
Feketedési görbe a filmek esetén. Adott megvilágítás
hatására a fény hogyan feketedik.

Feketedés logaritmikus. A filmre jutó és átjutó fény aránya.
Ha mind átjut, akkor nincs 0.
1/10-ét engedi át = 1
1/100-át = 2
1/1000 = 3

Van egy alapfátyol. Nem nulláról indul. Alapfátyol.
x tengelyen a 

Egy idő után eléri a legnagyobb feketedés, utána lekonyul.
Egy idő után roncsolja az ezüstöt.

Fontos a meredekség. Keménységgel összefügg. Meredek
kontrasztos, lapos lágy, nem kontrasztos.

Hol kezd feketedni.

** Mérőkamerák
Belső tájékozás ismerte. Vetítési középpont és képsík
egymáshoz való viszonya. Kameraállandó.
Képsík melyi pontja fölött, alatt.

Képfőpont. Az amelyik a vetítési középpont képsíkra
eső merőleges vetülete.

Optikai elrajzolás ismerete. Jobb ha külön vesszük a belső
tájékozástól. Optikai renszer nem teljesen a centrális
szerint képez. Lyukkamera a tökéletes. Optikán többszörösen
megtörő fény. Belépő és kilépő sugár szögének különbsége.

Nagy képméret. Pontos méréshez kell. Kiegészítő információ.
Magasságmérő, óra, libella...

Digitális kameránál az exif adatokban kiegészítő információ.

Exponált filmen a képi koordináta renszer. Keretjelek a kameráknál.
A fénykép felvételen a képi koordináta renszert határozza
meg. Rézau háló, illetve keretjelek.

** Digitális mérőképek
Digitális kép szabályos adatmodell. Pixelek mennyiségi infót
tartalmaz. Objektum spektrális és radiometriai adataival 
arányos. Geom, spekt, radio, időbeli felbontás.

Helyigény. pixel, sor, oszlop, radiometriai felbontás

V = ns * n oszlop * sáv * radometriai felbontás.

bit vagy bájt a felbontás Számítógépnél bájt a felbontás.

12 bit is 2 bájton tárolt.

** Digit mérőkam csoportosítása
Kép szenzorok, sorszenzorok. Ez a két nagy csoport.

** Korszerű digitális mérőkamera
Vexel ultracam leginkább használatos. Magyar 

ULTRACAM D, X, Xp képszenzoros

Sorszenzoros Leica ADS

** Sztereoszkopikus látás
3 feltétel 

képpár, tájékozás, képek szétválasztás

Képpár két külön álláspont, de ugyan az az objektum
parallaxis

tájékozás: zavartalan.

Jobb szem jobb kép

** Szétválasztás
- térben, tükrös, lencsés
- időben folyadékkristályos
- spektrálisan anaglif
** Normál sztereogram
Már tájékozott a sztereogram.
Normál sztereogramnál a bázisra merőleges kameratengellyel
készülnek a felvételek. Egyszerűbb számítás. Kis szögek
függvényeivel nem kellett foglalnkozni.

\Delta h = ...

h_0-t érdemes kieelni. Olyan mértékegység ami kell.

\delta p / p' / \delta p 

Egy arány. Nem kell átváltani. Repülési magasság mekkora
része a magasság.
** Analóg fotogammetria
mechanikai vagy optikai eszközökkel állítjuk helyre.

** Analitikus
Analitikus, mérjük számolunk, mérő

** Digitális
digitális képek, digitális kiértékelés
pixel, képi térbeli koord

** Téjékozás
Belső vetítési sík és kép viszonya
képfőpont eltolódás és kamera állandó.

Analóg képeknél kell a keretjel is.

Digitális képnél nem kell keretjel.



** Külső tájék
Már tájékozott képünk 6 paraméter
x, y, z, x_0, y_0, z_0, xc, yc, zc

Koordináta tngelyek körüli forgatás
\omega, \phi, \kappa


** Többképes fogo
Egymáshoz tájékozni. Relatív vagy kölcsönös tájékozás
Kapcsoló pontok vagy gruber pontok

5 paraméter 6 pont 1 fölös mérés.

1 pont 1 egyenlet. Relatív tájékozásra térmodell jön létre
objektum lekicsinyített képe.

Térmodell abszolút értelem.

3 koordináta eltolás és három forgatási szög.

Abszolút eltol, beforgat és méretarány összesen 7 parméteres
transzformáció. Geodéziában sokat használjuk.

1 * 6 

12 összesen.

Relatív 5 sokféle lehet!
5 szögérték, egy adott egységnyi.
2 távolság 3 szög

Sokféle fontos. Műszerek hozzá tájékozásnál volt fontos!

** UAV
pilóta nélküli eszközök.
Kategóriák

- nyílt open
- speciális specialised
- engedélyköteles certified

Nyílt kategóriával foglalkoztunk.
UAV felmérés a határokat túlléphetjük.

Mit léphetünk túl. Folyamatos eszköz követés. Gyakran
nem oldható meg. Urban canyon, erdő nem mindig!

120 m korlát is probléma lehet.

** Kérdés
Nem volt. Úgy kezdjük a félévet, hogy ne legyen gond.

* Idei anyag

** Fotogammetriai munkafolyamat

kb. 180 éves múlt

19. század elején daguerre-lips eljárás 1839?
Azért ez, mert a párizsi akadémia megvette és
ingyen elérhetővé tette. Dagerrotipia magyarul
megjlent 1840-es évek elején magyarok is.

19. század végén az elve. Meiderbaur cikke.
Újsághy Zsigmond erdőmérnök hallgató.

Elsősorban mennyiségi információ objektum mérete.

** ASPRS
1980-as def.

tárgyakról és környezetről megbízható információ
előállítás művészete, tudománya. fényképek és más
elektroágneses sugárzás készítés mérés és értelmezés

Fotointerpretáció a következő félévben.

art science technology, de alapvetően tudomány.
Művészi oldal az építészeti fotogammetria.

** Csoportosítás
Ismételtük

** Analóg fotogammetria
első félévben volt

Egy képes műszerek képtranszformátorok.
Sík, képtarszformátor SEG, LUZ átrajzoló

két képes a benti KERN pg műszer, Vild műszerei

Multiplex több képes vetítő

** Analitikus fotogammetria
mono és sztereokomparaátor

** Digitális fotogammetria
Elsődleges és másodlagos.

Másodlagos meglévő eljárással Elsődleges, digitális mérőkamerával.

Digitáilis képek és fotogammetriai szoftver és speciális
hardver eszköz.

Fotogammetriai szoftver, ami munkafolyamatot biztosítja.
Kép tájékozás és kiértékelés

Speciális hardverek 3D megjelenítők. Sztereo monitorok,
3D egér. Z kerék, amivel mérőjel magasságát állíthatjuk.

** Jelenlegi 
Leica RC30 (Wild RC-20)

Z/I imagink RMK (Zeiss RMK Top)

HM Zrínyi videója. Utolsó misszió. Lezárult korszak.
Ma már analóg kamerával nem dolgozik senki.

Analóg mérőkamerák jellemzői nem részleteztük.

** Fotogammetriai szkennerek
- Leica Geosystem

Mi a különbség?
Nem a felbontás, hanem a geometriai pontosság.

Asztali 3600 dpi sem ritka

25.4/3600
[1] 0.007055556

7 mikront általában tudja egy jobb szkenner.

Fontos a geometriai pontosság. 2 kép egymás után kivonjuk
Nagyon durva (10 pixeles eltérés is lehet), ahogy húzza.

Fotogammetria 10 um mellett 2 um RMSE!!!!

Méret Nagy méretet keeli

FÖMI DLA Leica Geosytem DSW 700

Kamerát mozgat a film előtt több képet csinál, abból
teszi össze!

Vexcel Imaging UltraScan = több érzékelőből ez is!


Z/I Imagin Phot can HM Zrínyi archívum digitális.
30*30-as filmek nem fért be.

Vehrli RasterMaster ezt is tudja.

Ingyen kapcsolatokon kapták, angliából jött.
Egy idő után nem kellenek. Teljes értéket kap a digitalizáltság.

Geometriai pontosság a legfontosabb a megfelelő
képméret mellett.

Vexcel UltraCamD
Vexcel UltraScan

Gráci professzor dogozta ki az eljárást.
9 kis szenzor előállítása töredék költség. tömeggyártásból
készült fullframe szenzorok!

Rögtön piacvezető.

** Megvan a digitális kép
Szoftver tudja a belső és külső tájékozást
relatív és abszolút

Kimenet ortofotók, ortofotó mozaikok. Térbeli
méréseket végezni a képpárokon. Kéegyeztetésekből
automatikusan pontfelhőt állítunk elő.

Térbeli mérések, ortofotó a számítás technika fejlődése
Ma már feldolgozás Imaga Matching automatikus képegyeztetés
és pontfelhő előállítása.

TRUE orto, pontfelhőn mérhetünk. Élek keresése pl. épület.

** Belső tájékozás
minimum 3 paraméter (c, F'(\ksi_0, \eta_0))

TopoxMap ablaka.

Keretjelek megmérése. Digitális fotogammetriai szoftverekben
a keretjel mérése automatizálható.

Korszerűbb kameránál a keretjel kódolt.

Sok szkenner szkenneléskor detektálja a keretjelet.
Ki tudja a fájl mellé tenni a keretjel koordinátáját!

Másodlagos képeknél a keretjelek megmérése jól automatizálható.

Agisoft PhotoScan
Kamera állandó, kalbrációs paraméterek.

** Relatív tájékozás
Kölcsönös tájékozás

5 paraméter több minden is lehet.

x iárnyú bázis rögítve. Jobb képet tologatom. forgatom.

Bal képet rögítem, nem kell továbbmenetnél mozgatni. Nem
kell elrontani a képpárokat. Korábban a
kivetített 5 paraméter

b_x válsztott, b_y, b_z, \phi_2, \omega_2, \kappa_2

*** Csak szögekkel
\phi_1, (\omega_1), \kappa_1, \phi_2, \omega_2, \kappa_2

*** Realív
Grube pontok

Koplanaritás kapcsolópontok egy síkon.

Ma már jól automatizált. Gyorsítani lehet, ha egy-két
paramétert meghatározunk, akkor csak finomítunk.

Jó kezdeti paraméterekkel gyorsabb.

5, de
Gyakorlatilag minimum 6 pont!

**** Képegyeztetés
Ma ez is már fontos lehet.

*** Abszolút tájékozás
6 paraméter X_0, Y_0, Z_0, \phi_0, \omega_0, \kappa_0

Jellemzően, ha vannak elérhető direkt tájékozás,
de indirekt úton pontosítjuk.

Direkt a kép készítésekor határozzuk meg a hat

GNSS X_0, Y_0, Z_0,
IMU/INS: \phi_0, \omega_0, \kappa_0

90-es évektől már van direkt információ. Manapság is
indirekt úton pontosítunk. Illesztő pontokk
IP, GPC (ground control points) kollinearitás elvével
történik.

Kollinearitás illesztőpont, illesztőpont képe és vetítési középpont.

3 egymást megsző egyenes. metszés, vetítési középpont és
forgatási szögek meghatározása.

1 ilelsztőpont két egyenlet, két egyenletekből három pont kell!

Relatív tájékozás után abszoltút tájékozás.

3 illesztőpont a hét paramétert is meghatározhatóvá teszi.

Illesztő pont, mid a képen és a terepen is jól azonosítható!

** Ortofotó előállítása
Tájékozott fényképből előállítható. Felületet definiálni.

Síkfelólet, homlokzat modellje, borított felszín modell.
visszavetítjük. több 100 több 1000 képből manapság. Ortofotó
mozaik.

Ez lehet az egyik kimenet.

** Ortorektifikáció
Raszter transzformáció. Fordítva haladunk.
Definiáljuk a kimeneti ortofotónkat. Milyen területre,
milyen felbontással készíten.

Veszem a pixelt térbeli egyenes a vetítési középponton,
ak képi pixelt másolom.

Ha nem sík területen, a domborzatmodellre vetítem
először. Pixelről pixelre a differenciális képátlakítás.

Fontos az újra mintavételezés resampling. Nem biztos, hogy
egy pixel. Hogyan veszem a több pixelből a mintát?

Milyen modellre? Ha DDM-re klasszikus, ha BFM, akkor true
ortofotó.

** Térbeli mérések
Manuális sztereofotogammetriai munkaállomáson. Térmodellen
irányzott pont, CAD szerű szoftveren rajzolunk (merőlege,
párhuzamos rajzolás)

Félautomatikus mérések. Több mintent jelent. Cursor-on-surface
kattintottm, s térmodellre a mérőjelet.
Bal kattint. Megkeresi a másik képen az epipoláris modell a képpáron.

Azután szabályos rácshálón maga kereste a 3D-t.

Manapság teljesen automatikusan minden pixelnek megkeressük
a párját. Sűrű pontfelhő ponthalmaz!

** Térbeli kép
Epipolásir sík a másik képen epipoláris egyenest határoz meg.
A szakaszon tudjuk ott a pont. Korreláltatjuk a képet,
megvan a pont.

** Image matching
Manapság ezek a legfontosabb kimenet.

Többféle van, majd részletesen vesszük.
Egy pontfelhő áll elő eredményként. Zajos, elszállt
pontok, kiszűrése. Modellek előállítása

BFM borított felszín modell, DSM digital surface modell.

Ezzel a félév során foglalkozunk.

** Nem képegyeztetés pontfelhő
Még fogunk foglalkozni lézerszkennerrel.
Egyéb pontfelhő feldolgozások.

Első ismétlő ZH. CV-sek miatt a harmadik héten.
18-án kerülne sor.

10 perces valami. Hasonló a beugróhoz.
